#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x9cef51a8, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x7f609f98, __VMLINUX_SYMBOL_STR(of_phy_is_fixed_link) },
	{ 0x6b834fb4, __VMLINUX_SYMBOL_STR(netdev_info) },
	{ 0xf6789fdc, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x65e75cb6, __VMLINUX_SYMBOL_STR(__list_del_entry) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xc70130a9, __VMLINUX_SYMBOL_STR(phy_disconnect) },
	{ 0x1c9c7a13, __VMLINUX_SYMBOL_STR(of_mdio_find_bus) },
	{ 0x86be6720, __VMLINUX_SYMBOL_STR(hwmon_device_register_with_groups) },
	{ 0x732b8a82, __VMLINUX_SYMBOL_STR(dev_mc_unsync) },
	{ 0x349cba85, __VMLINUX_SYMBOL_STR(strchr) },
	{ 0xa6634d96, __VMLINUX_SYMBOL_STR(of_phy_deregister_fixed_link) },
	{ 0xe44a7baa, __VMLINUX_SYMBOL_STR(phy_stop) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0x435d8774, __VMLINUX_SYMBOL_STR(of_property_read_u32_index) },
	{ 0xe964e0a4, __VMLINUX_SYMBOL_STR(genphy_read_status) },
	{ 0x16e06b09, __VMLINUX_SYMBOL_STR(of_parse_phandle) },
	{ 0xaef9b7ae, __VMLINUX_SYMBOL_STR(phy_resume) },
	{ 0xd29735d, __VMLINUX_SYMBOL_STR(genphy_update_link) },
	{ 0x9970441d, __VMLINUX_SYMBOL_STR(dev_uc_add) },
	{ 0x16789d50, __VMLINUX_SYMBOL_STR(switchdev_port_bridge_setlink) },
	{ 0x9ebc3586, __VMLINUX_SYMBOL_STR(__mdiobus_register) },
	{ 0x4a0796f, __VMLINUX_SYMBOL_STR(switchdev_port_fdb_dump) },
	{ 0x3167171c, __VMLINUX_SYMBOL_STR(hwmon_device_unregister) },
	{ 0x113008f4, __VMLINUX_SYMBOL_STR(skb_copy_and_csum_dev) },
	{ 0xee6b4dd3, __VMLINUX_SYMBOL_STR(mdiobus_get_phy) },
	{ 0x21e66d84, __VMLINUX_SYMBOL_STR(skb_copy) },
	{ 0xd2da1048, __VMLINUX_SYMBOL_STR(register_netdevice_notifier) },
	{ 0xd7dd8451, __VMLINUX_SYMBOL_STR(netif_carrier_off) },
	{ 0xf9f45f89, __VMLINUX_SYMBOL_STR(phy_ethtool_gset) },
	{ 0xb224b3ec, __VMLINUX_SYMBOL_STR(dev_set_allmulti) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0xdbe8baac, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x3a7f9fcd, __VMLINUX_SYMBOL_STR(__netpoll_setup) },
	{ 0x7926459b, __VMLINUX_SYMBOL_STR(switchdev_port_fdb_del) },
	{ 0xb34e82fe, __VMLINUX_SYMBOL_STR(of_get_phy_mode) },
	{ 0x3bf894da, __VMLINUX_SYMBOL_STR(switchdev_port_bridge_getlink) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0x821bc486, __VMLINUX_SYMBOL_STR(mdiobus_unregister) },
	{ 0xc499ae1e, __VMLINUX_SYMBOL_STR(kstrdup) },
	{ 0x837bc10d, __VMLINUX_SYMBOL_STR(__platform_driver_register) },
	{ 0x300bdde2, __VMLINUX_SYMBOL_STR(of_mdio_parse_addr) },
	{ 0x343a1a8, __VMLINUX_SYMBOL_STR(__list_add) },
	{ 0x9d0d6206, __VMLINUX_SYMBOL_STR(unregister_netdevice_notifier) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0xc3a7591e, __VMLINUX_SYMBOL_STR(devm_mdiobus_alloc_size) },
	{ 0xa404564, __VMLINUX_SYMBOL_STR(phy_ethtool_get_eee) },
	{ 0xec82b576, __VMLINUX_SYMBOL_STR(__pskb_pull_tail) },
	{ 0xe4ca266e, __VMLINUX_SYMBOL_STR(netpoll_send_skb_on_dev) },
	{ 0x76693230, __VMLINUX_SYMBOL_STR(phy_print_status) },
	{ 0x604359c8, __VMLINUX_SYMBOL_STR(of_phy_register_fixed_link) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0x7832a8fa, __VMLINUX_SYMBOL_STR(phy_start) },
	{ 0x11089ac7, __VMLINUX_SYMBOL_STR(_ctype) },
	{ 0x752aeb9e, __VMLINUX_SYMBOL_STR(dev_err) },
	{ 0x37befc70, __VMLINUX_SYMBOL_STR(jiffies_to_msecs) },
	{ 0x6d294e43, __VMLINUX_SYMBOL_STR(clock_t_to_jiffies) },
	{ 0xdea51a39, __VMLINUX_SYMBOL_STR(device_find_child) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x489dd187, __VMLINUX_SYMBOL_STR(of_find_net_device_by_node) },
	{ 0xb5bcd784, __VMLINUX_SYMBOL_STR(__netpoll_free_async) },
	{ 0x535890a0, __VMLINUX_SYMBOL_STR(free_netdev) },
	{ 0x328a05f1, __VMLINUX_SYMBOL_STR(strncpy) },
	{ 0x63eea3ef, __VMLINUX_SYMBOL_STR(register_netdev) },
	{ 0x4272dccd, __VMLINUX_SYMBOL_STR(netif_receive_skb) },
	{ 0x73e20c1c, __VMLINUX_SYMBOL_STR(strlcpy) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xfdf8f58f, __VMLINUX_SYMBOL_STR(skb_push) },
	{ 0xfed0a669, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x521445b, __VMLINUX_SYMBOL_STR(list_del) },
	{ 0x8ad94e3c, __VMLINUX_SYMBOL_STR(dev_remove_pack) },
	{ 0x373db350, __VMLINUX_SYMBOL_STR(kstrtoint) },
	{ 0x86b82b64, __VMLINUX_SYMBOL_STR(fixed_phy_set_link_update) },
	{ 0x4c7ab66e, __VMLINUX_SYMBOL_STR(phy_suspend) },
	{ 0x77b5037e, __VMLINUX_SYMBOL_STR(of_get_child_by_name) },
	{ 0x4c560e8e, __VMLINUX_SYMBOL_STR(netif_device_attach) },
	{ 0x64effb2a, __VMLINUX_SYMBOL_STR(netif_device_detach) },
	{ 0x2005e93f, __VMLINUX_SYMBOL_STR(__alloc_skb) },
	{ 0x893710b7, __VMLINUX_SYMBOL_STR(phy_connect_direct) },
	{ 0xf8dfe3ad, __VMLINUX_SYMBOL_STR(put_device) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x4a6761ad, __VMLINUX_SYMBOL_STR(kfree_skb) },
	{ 0x702291be, __VMLINUX_SYMBOL_STR(alloc_netdev_mqs) },
	{ 0x77c29585, __VMLINUX_SYMBOL_STR(eth_type_trans) },
	{ 0xe41b0acf, __VMLINUX_SYMBOL_STR(pskb_expand_head) },
	{ 0x9c80dbd9, __VMLINUX_SYMBOL_STR(genphy_config_init) },
	{ 0x19f204f, __VMLINUX_SYMBOL_STR(of_phy_connect) },
	{ 0x1c49fc83, __VMLINUX_SYMBOL_STR(netdev_err) },
	{ 0x1df9d6f5, __VMLINUX_SYMBOL_STR(of_get_property) },
	{ 0xe61bcaa3, __VMLINUX_SYMBOL_STR(ether_setup) },
	{ 0x98212134, __VMLINUX_SYMBOL_STR(dev_uc_unsync) },
	{ 0x147fb690, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xd7a5c0a6, __VMLINUX_SYMBOL_STR(switchdev_port_fdb_add) },
	{ 0xc64ff798, __VMLINUX_SYMBOL_STR(skb_pull_rcsum) },
	{ 0x1c2d7653, __VMLINUX_SYMBOL_STR(of_get_next_available_child) },
	{ 0x657b2089, __VMLINUX_SYMBOL_STR(get_device) },
	{ 0x822137e2, __VMLINUX_SYMBOL_STR(arm_heavy_mb) },
	{ 0x1169644b, __VMLINUX_SYMBOL_STR(of_node_get) },
	{ 0xf1fab087, __VMLINUX_SYMBOL_STR(dev_set_promiscuity) },
	{ 0x3a3d95f5, __VMLINUX_SYMBOL_STR(of_get_parent) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x637da533, __VMLINUX_SYMBOL_STR(phy_attached_info) },
	{ 0xccef93e1, __VMLINUX_SYMBOL_STR(___pskb_trim) },
	{ 0xe12b8b63, __VMLINUX_SYMBOL_STR(phy_ethtool_set_eee) },
	{ 0xf9e73082, __VMLINUX_SYMBOL_STR(scnprintf) },
	{ 0xbdd9a237, __VMLINUX_SYMBOL_STR(dev_uc_del) },
	{ 0x4d73c532, __VMLINUX_SYMBOL_STR(dev_uc_sync) },
	{ 0xaa7d42d1, __VMLINUX_SYMBOL_STR(dev_warn) },
	{ 0x3d8dc21b, __VMLINUX_SYMBOL_STR(unregister_netdev) },
	{ 0x5e020f28, __VMLINUX_SYMBOL_STR(switchdev_port_bridge_dellink) },
	{ 0x8f678b07, __VMLINUX_SYMBOL_STR(__stack_chk_guard) },
	{ 0x95063e7a, __VMLINUX_SYMBOL_STR(phy_mii_ioctl) },
	{ 0xaac14c2e, __VMLINUX_SYMBOL_STR(phy_ethtool_sset) },
	{ 0xb81960ca, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0x4360a38, __VMLINUX_SYMBOL_STR(dev_add_pack) },
	{ 0x99bb8806, __VMLINUX_SYMBOL_STR(memmove) },
	{ 0xe113bbbc, __VMLINUX_SYMBOL_STR(csum_partial) },
	{ 0xcb62ec7d, __VMLINUX_SYMBOL_STR(consume_skb) },
	{ 0x8411815c, __VMLINUX_SYMBOL_STR(of_phy_find_device) },
	{ 0x36cf4f03, __VMLINUX_SYMBOL_STR(platform_driver_unregister) },
	{ 0x5b344826, __VMLINUX_SYMBOL_STR(dev_queue_xmit) },
	{ 0x2deb66d0, __VMLINUX_SYMBOL_STR(of_property_read_variable_u32_array) },
	{ 0x9cfd625d, __VMLINUX_SYMBOL_STR(skb_put) },
	{ 0x42e28e96, __VMLINUX_SYMBOL_STR(of_node_put) },
	{ 0xc43902e8, __VMLINUX_SYMBOL_STR(devm_kmalloc) },
	{ 0xbdc15b4, __VMLINUX_SYMBOL_STR(dev_mc_sync) },
	{ 0xfeca89e4, __VMLINUX_SYMBOL_STR(genphy_restart_aneg) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=";

MODULE_ALIAS("of:N*T*Cmarvell,dsa");
MODULE_ALIAS("of:N*T*Cmarvell,dsaC*");
