#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x9cef51a8, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x981339cc, __VMLINUX_SYMBOL_STR(pnfs_unregister_layoutdriver) },
	{ 0x828655aa, __VMLINUX_SYMBOL_STR(nfs4_schedule_session_recovery) },
	{ 0x3dd6eacc, __VMLINUX_SYMBOL_STR(pnfs_nfs_generic_sync) },
	{ 0xf6789fdc, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x65e75cb6, __VMLINUX_SYMBOL_STR(__list_del_entry) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xf9a482f9, __VMLINUX_SYMBOL_STR(msleep) },
	{ 0xaf5bf6ef, __VMLINUX_SYMBOL_STR(nfs_debug) },
	{ 0x5fc56a46, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0xc30eebb2, __VMLINUX_SYMBOL_STR(nfs4_pnfs_ds_connect) },
	{ 0xb1debaea, __VMLINUX_SYMBOL_STR(pnfs_generic_clear_request_commit) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0x292db41e, __VMLINUX_SYMBOL_STR(page_address) },
	{ 0x78128e0f, __VMLINUX_SYMBOL_STR(nfs_init_cinfo) },
	{ 0x19f462ab, __VMLINUX_SYMBOL_STR(kfree_call_rcu) },
	{ 0xb78c81c1, __VMLINUX_SYMBOL_STR(nfs_initiate_commit) },
	{ 0xedf0d140, __VMLINUX_SYMBOL_STR(pnfs_error_mark_layout_for_return) },
	{ 0x3b304455, __VMLINUX_SYMBOL_STR(nfs4_pnfs_ds_put) },
	{ 0xbe511b9, __VMLINUX_SYMBOL_STR(put_rpccred) },
	{ 0x2a3aa678, __VMLINUX_SYMBOL_STR(_test_and_clear_bit) },
	{ 0x54bef45, __VMLINUX_SYMBOL_STR(layoutstats_timer) },
	{ 0xc87c1f84, __VMLINUX_SYMBOL_STR(ktime_get) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0x6e3e437e, __VMLINUX_SYMBOL_STR(init_user_ns) },
	{ 0x643d9ba1, __VMLINUX_SYMBOL_STR(groups_free) },
	{ 0xc54808b0, __VMLINUX_SYMBOL_STR(nfs4_mark_deviceid_unavailable) },
	{ 0x48cddcb6, __VMLINUX_SYMBOL_STR(__tracepoint_nfs4_pnfs_commit_ds) },
	{ 0x4de83430, __VMLINUX_SYMBOL_STR(nfs4_decode_mp_ds_addr) },
	{ 0xe62aa2bc, __VMLINUX_SYMBOL_STR(nfs_initiate_pgio) },
	{ 0x2c4b3abb, __VMLINUX_SYMBOL_STR(nfs4_set_rw_stateid) },
	{ 0x8e0fea8a, __VMLINUX_SYMBOL_STR(pnfs_generic_commit_pagelist) },
	{ 0xddfee4dd, __VMLINUX_SYMBOL_STR(__alloc_pages_nodemask) },
	{ 0x8afb1e6c, __VMLINUX_SYMBOL_STR(pnfs_generic_recover_commit_reqs) },
	{ 0x343a1a8, __VMLINUX_SYMBOL_STR(__list_add) },
	{ 0x28057c5a, __VMLINUX_SYMBOL_STR(nfs41_setup_sequence) },
	{ 0x5b8b6921, __VMLINUX_SYMBOL_STR(nfs4_sequence_done) },
	{ 0xca6ef829, __VMLINUX_SYMBOL_STR(xdr_reserve_space) },
	{ 0x567f6332, __VMLINUX_SYMBOL_STR(pnfs_generic_pg_test) },
	{ 0x5bfdcee4, __VMLINUX_SYMBOL_STR(nfs4_schedule_lease_recovery) },
	{ 0xfa28ef53, __VMLINUX_SYMBOL_STR(pnfs_update_layout) },
	{ 0x70733fd1, __VMLINUX_SYMBOL_STR(make_kgid) },
	{ 0xea8c9aa5, __VMLINUX_SYMBOL_STR(rpc_exit) },
	{ 0x9a24ff4c, __VMLINUX_SYMBOL_STR(pnfs_generic_pg_cleanup) },
	{ 0xa5894787, __VMLINUX_SYMBOL_STR(pnfs_generic_write_commit_done) },
	{ 0xa405bc0, __VMLINUX_SYMBOL_STR(rpc_delay) },
	{ 0xdd0a2ba2, __VMLINUX_SYMBOL_STR(strlcat) },
	{ 0x9880b886, __VMLINUX_SYMBOL_STR(pnfs_generic_layout_insert_lseg) },
	{ 0xdb12c0e6, __VMLINUX_SYMBOL_STR(xdr_init_decode_pages) },
	{ 0xbac3cbf2, __VMLINUX_SYMBOL_STR(ns_to_timespec64) },
	{ 0xbddbd222, __VMLINUX_SYMBOL_STR(from_kuid) },
	{ 0x49eabfa8, __VMLINUX_SYMBOL_STR(rpc_call_start) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x71c90087, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x2419c7aa, __VMLINUX_SYMBOL_STR(__cpu_online_mask) },
	{ 0x6a86f3a, __VMLINUX_SYMBOL_STR(nfs40_setup_sequence) },
	{ 0x60f0a7fd, __VMLINUX_SYMBOL_STR(pnfs_read_resend_pnfs) },
	{ 0x6968edcb, __VMLINUX_SYMBOL_STR(nfs4_find_get_deviceid) },
	{ 0xcef801f7, __VMLINUX_SYMBOL_STR(from_kgid) },
	{ 0x42d39550, __VMLINUX_SYMBOL_STR(nfs4_find_or_create_ds_client) },
	{ 0x3d575f18, __VMLINUX_SYMBOL_STR(rpc_max_payload) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x4dfe2172, __VMLINUX_SYMBOL_STR(nfs_pageio_reset_write_mds) },
	{ 0x521445b, __VMLINUX_SYMBOL_STR(list_del) },
	{ 0x2469810f, __VMLINUX_SYMBOL_STR(__rcu_read_unlock) },
	{ 0xed1de3e2, __VMLINUX_SYMBOL_STR(pnfs_layout_mark_request_commit) },
	{ 0x38e8437e, __VMLINUX_SYMBOL_STR(pnfs_destroy_layout) },
	{ 0xf70e4a4d, __VMLINUX_SYMBOL_STR(preempt_schedule_notrace) },
	{ 0xa2804311, __VMLINUX_SYMBOL_STR(nfs4_pnfs_ds_add) },
	{ 0x45210d2b, __VMLINUX_SYMBOL_STR(pnfs_layoutcommit_inode) },
	{ 0x8d8a88f8, __VMLINUX_SYMBOL_STR(pnfs_put_lseg) },
	{ 0xf69ee7fe, __VMLINUX_SYMBOL_STR(contig_page_data) },
	{ 0x52d09f74, __VMLINUX_SYMBOL_STR(nfs4_put_deviceid_node) },
	{ 0x3e603670, __VMLINUX_SYMBOL_STR(pnfs_report_layoutstat) },
	{ 0xed15fb41, __VMLINUX_SYMBOL_STR(nfs4_print_deviceid) },
	{ 0x1a720c15, __VMLINUX_SYMBOL_STR(pnfs_set_layoutcommit) },
	{ 0x5d3ad50e, __VMLINUX_SYMBOL_STR(pnfs_generic_scan_commit_lists) },
	{ 0x69d3558d, __VMLINUX_SYMBOL_STR(pnfs_generic_rw_release) },
	{ 0x9f9d0265, __VMLINUX_SYMBOL_STR(__free_pages) },
	{ 0x37d79ccd, __VMLINUX_SYMBOL_STR(make_kuid) },
	{ 0x50639574, __VMLINUX_SYMBOL_STR(nfs4_schedule_stateid_recovery) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0xba8bb333, __VMLINUX_SYMBOL_STR(___ratelimit) },
	{ 0xe3b178a, __VMLINUX_SYMBOL_STR(nfs4_test_deviceid_unavailable) },
	{ 0xa02df320, __VMLINUX_SYMBOL_STR(nfs_map_string_to_numeric) },
	{ 0xf999267e, __VMLINUX_SYMBOL_STR(pnfs_generic_commit_release) },
	{ 0xdfdaace4, __VMLINUX_SYMBOL_STR(rpc_sleep_on) },
	{ 0x8f5a84ce, __VMLINUX_SYMBOL_STR(pnfs_generic_pg_readpages) },
	{ 0x147fb690, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x65994f1, __VMLINUX_SYMBOL_STR(xdr_encode_opaque_fixed) },
	{ 0x5900a131, __VMLINUX_SYMBOL_STR(pnfs_read_done_resend_to_mds) },
	{ 0xe5919cb1, __VMLINUX_SYMBOL_STR(xdr_encode_opaque) },
	{ 0x65ddff9a, __VMLINUX_SYMBOL_STR(rpc_restart_call_prepare) },
	{ 0x7fe1f1c5, __VMLINUX_SYMBOL_STR(rpc_wake_up_queued_task) },
	{ 0x3e2b0ba6, __VMLINUX_SYMBOL_STR(groups_alloc) },
	{ 0xe617511c, __VMLINUX_SYMBOL_STR(pnfs_generic_pg_writepages) },
	{ 0x6b135410, __VMLINUX_SYMBOL_STR(pnfs_generic_prepare_to_resend_writes) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x5edd7f84, __VMLINUX_SYMBOL_STR(__tracepoint_nfs4_pnfs_read) },
	{ 0x6fec18c3, __VMLINUX_SYMBOL_STR(pnfs_write_done_resend_to_mds) },
	{ 0x4ddef95c, __VMLINUX_SYMBOL_STR(rpc_wake_up) },
	{ 0x8f678b07, __VMLINUX_SYMBOL_STR(__stack_chk_guard) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0xd28e7b0d, __VMLINUX_SYMBOL_STR(rpc_count_iostats_metrics) },
	{ 0x13b06a5f, __VMLINUX_SYMBOL_STR(xdr_inline_decode) },
	{ 0xd576bffd, __VMLINUX_SYMBOL_STR(__tracepoint_nfs4_pnfs_write) },
	{ 0xb81960ca, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0xca54fee, __VMLINUX_SYMBOL_STR(_test_and_set_bit) },
	{ 0xdeb69a40, __VMLINUX_SYMBOL_STR(rpc_lookup_generic_cred) },
	{ 0x2d572a5, __VMLINUX_SYMBOL_STR(nfs_pageio_reset_read_mds) },
	{ 0x8d522714, __VMLINUX_SYMBOL_STR(__rcu_read_lock) },
	{ 0x11e48144, __VMLINUX_SYMBOL_STR(nfs4_init_deviceid_node) },
	{ 0x49ebacbd, __VMLINUX_SYMBOL_STR(_clear_bit) },
	{ 0x23fa4443, __VMLINUX_SYMBOL_STR(param_ops_uint) },
	{ 0xb0e55010, __VMLINUX_SYMBOL_STR(nfs_remove_bad_delegation) },
	{ 0x4301b153, __VMLINUX_SYMBOL_STR(xdr_set_scratch_buffer) },
	{ 0x1b8cb12a, __VMLINUX_SYMBOL_STR(nfs_writeback_update_inode) },
	{ 0xca016137, __VMLINUX_SYMBOL_STR(pnfs_register_layoutdriver) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=";

