#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x9cef51a8, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x10ab577b, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0xca8c58e3, __VMLINUX_SYMBOL_STR(iget_failed) },
	{ 0xf6789fdc, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x405c1144, __VMLINUX_SYMBOL_STR(get_seconds) },
	{ 0xabfed5c8, __VMLINUX_SYMBOL_STR(drop_nlink) },
	{ 0x97ee2277, __VMLINUX_SYMBOL_STR(mark_buffer_dirty_inode) },
	{ 0x1d810aa0, __VMLINUX_SYMBOL_STR(generic_file_llseek) },
	{ 0x6ed86506, __VMLINUX_SYMBOL_STR(__mark_inode_dirty) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0x97255bdf, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x60a13e90, __VMLINUX_SYMBOL_STR(rcu_barrier) },
	{ 0x292db41e, __VMLINUX_SYMBOL_STR(page_address) },
	{ 0x31c46dca, __VMLINUX_SYMBOL_STR(block_write_begin) },
	{ 0xc72f6987, __VMLINUX_SYMBOL_STR(pagecache_get_page) },
	{ 0x25820c64, __VMLINUX_SYMBOL_STR(fs_overflowuid) },
	{ 0xb5198b77, __VMLINUX_SYMBOL_STR(_raw_read_lock) },
	{ 0x955db142, __VMLINUX_SYMBOL_STR(__lock_page) },
	{ 0x58ac6911, __VMLINUX_SYMBOL_STR(__lock_buffer) },
	{ 0x2dec9106, __VMLINUX_SYMBOL_STR(inc_nlink) },
	{ 0x8951783, __VMLINUX_SYMBOL_STR(block_read_full_page) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0xdbe8baac, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x309a8694, __VMLINUX_SYMBOL_STR(mount_bdev) },
	{ 0xe80a4b2c, __VMLINUX_SYMBOL_STR(d_add) },
	{ 0x8f16c859, __VMLINUX_SYMBOL_STR(generic_read_dir) },
	{ 0xc0ddafd9, __VMLINUX_SYMBOL_STR(__getblk_gfp) },
	{ 0x28aa6a67, __VMLINUX_SYMBOL_STR(call_rcu) },
	{ 0xfaf9dc0d, __VMLINUX_SYMBOL_STR(unlock_buffer) },
	{ 0xbfca67ad, __VMLINUX_SYMBOL_STR(truncate_setsize) },
	{ 0x70733fd1, __VMLINUX_SYMBOL_STR(make_kgid) },
	{ 0x5559244c, __VMLINUX_SYMBOL_STR(__insert_inode_hash) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0x5f754e5a, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xbddbd222, __VMLINUX_SYMBOL_STR(from_kuid) },
	{ 0x706c5a65, __VMLINUX_SYMBOL_STR(preempt_count_sub) },
	{ 0x47ec9fac, __VMLINUX_SYMBOL_STR(__bread_gfp) },
	{ 0x5a32f871, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x71c90087, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0xdfd61436, __VMLINUX_SYMBOL_STR(_raw_write_unlock) },
	{ 0x4bc9fa80, __VMLINUX_SYMBOL_STR(_raw_read_unlock) },
	{ 0xbcff3d85, __VMLINUX_SYMBOL_STR(kunmap) },
	{ 0xcef801f7, __VMLINUX_SYMBOL_STR(from_kgid) },
	{ 0xd26e0e90, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0xfed0a669, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x1e9eb54b, __VMLINUX_SYMBOL_STR(set_nlink) },
	{ 0xd100acbd, __VMLINUX_SYMBOL_STR(_raw_write_lock) },
	{ 0x71ea0bb5, __VMLINUX_SYMBOL_STR(setattr_copy) },
	{ 0xde674486, __VMLINUX_SYMBOL_STR(page_symlink) },
	{ 0xa9d91222, __VMLINUX_SYMBOL_STR(sync_dirty_buffer) },
	{ 0xc3cc0830, __VMLINUX_SYMBOL_STR(truncate_pagecache) },
	{ 0x43b0c9c3, __VMLINUX_SYMBOL_STR(preempt_schedule) },
	{ 0xbeed5ae8, __VMLINUX_SYMBOL_STR(unlock_page) },
	{ 0xa23be2de, __VMLINUX_SYMBOL_STR(generic_file_read_iter) },
	{ 0x6087373b, __VMLINUX_SYMBOL_STR(inode_nohighmem) },
	{ 0xa726bd83, __VMLINUX_SYMBOL_STR(__brelse) },
	{ 0xbed2f853, __VMLINUX_SYMBOL_STR(inode_init_once) },
	{ 0xbc852264, __VMLINUX_SYMBOL_STR(invalidate_inode_buffers) },
	{ 0x666774aa, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0xd9ce8f0c, __VMLINUX_SYMBOL_STR(strnlen) },
	{ 0xfa65cc21, __VMLINUX_SYMBOL_STR(generic_file_mmap) },
	{ 0x2d41e8fa, __VMLINUX_SYMBOL_STR(kmap) },
	{ 0xf42c9c03, __VMLINUX_SYMBOL_STR(block_write_full_page) },
	{ 0x8783460d, __VMLINUX_SYMBOL_STR(block_write_end) },
	{ 0x512eee80, __VMLINUX_SYMBOL_STR(truncate_inode_pages_final) },
	{ 0x37d79ccd, __VMLINUX_SYMBOL_STR(make_kuid) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0xe8b464c2, __VMLINUX_SYMBOL_STR(generic_write_end) },
	{ 0x12126351, __VMLINUX_SYMBOL_STR(unlock_new_inode) },
	{ 0x4ada7514, __VMLINUX_SYMBOL_STR(kill_block_super) },
	{ 0xbeffe211, __VMLINUX_SYMBOL_STR(inode_newsize_ok) },
	{ 0x800fb92b, __VMLINUX_SYMBOL_STR(full_name_hash) },
	{ 0x147fb690, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xedf65a89, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0xb6a475eb, __VMLINUX_SYMBOL_STR(register_filesystem) },
	{ 0x53406d67, __VMLINUX_SYMBOL_STR(generic_file_write_iter) },
	{ 0x42aa798f, __VMLINUX_SYMBOL_STR(iput) },
	{ 0x324e8226, __VMLINUX_SYMBOL_STR(read_cache_page) },
	{ 0x1901f6ad, __VMLINUX_SYMBOL_STR(generic_file_fsync) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x490d389e, __VMLINUX_SYMBOL_STR(page_get_link) },
	{ 0x73f270da, __VMLINUX_SYMBOL_STR(ihold) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x40063b81, __VMLINUX_SYMBOL_STR(current_time) },
	{ 0x7940b12d, __VMLINUX_SYMBOL_STR(sync_filesystem) },
	{ 0xa9589e2a, __VMLINUX_SYMBOL_STR(block_truncate_page) },
	{ 0xfb09f771, __VMLINUX_SYMBOL_STR(sb_set_blocksize) },
	{ 0x831394aa, __VMLINUX_SYMBOL_STR(generic_readlink) },
	{ 0x4b06df9e, __VMLINUX_SYMBOL_STR(__bforget) },
	{ 0x268b4710, __VMLINUX_SYMBOL_STR(d_make_root) },
	{ 0x135b5d28, __VMLINUX_SYMBOL_STR(__block_write_begin) },
	{ 0x3fd074ca, __VMLINUX_SYMBOL_STR(mark_buffer_dirty) },
	{ 0x368f8aa8, __VMLINUX_SYMBOL_STR(unregister_filesystem) },
	{ 0x5bcf0a85, __VMLINUX_SYMBOL_STR(write_one_page) },
	{ 0xd642af8d, __VMLINUX_SYMBOL_STR(init_special_inode) },
	{ 0x8f678b07, __VMLINUX_SYMBOL_STR(__stack_chk_guard) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0xac598406, __VMLINUX_SYMBOL_STR(new_inode) },
	{ 0xca54fee, __VMLINUX_SYMBOL_STR(_test_and_set_bit) },
	{ 0x59ea0803, __VMLINUX_SYMBOL_STR(generic_file_splice_read) },
	{ 0xf229424a, __VMLINUX_SYMBOL_STR(preempt_count_add) },
	{ 0xd680cd2b, __VMLINUX_SYMBOL_STR(clear_inode) },
	{ 0x3a7a414a, __VMLINUX_SYMBOL_STR(d_instantiate) },
	{ 0x2ef3e65f, __VMLINUX_SYMBOL_STR(__put_page) },
	{ 0x72aa9bf5, __VMLINUX_SYMBOL_STR(generic_block_bmap) },
	{ 0xeb8bacd2, __VMLINUX_SYMBOL_STR(iget_locked) },
	{ 0x1d3e4f76, __VMLINUX_SYMBOL_STR(setattr_prepare) },
	{ 0x7635638a, __VMLINUX_SYMBOL_STR(generic_fillattr) },
	{ 0x2ec4fec7, __VMLINUX_SYMBOL_STR(inode_init_owner) },
	{ 0xdf929370, __VMLINUX_SYMBOL_STR(fs_overflowgid) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=";

