#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x2c197ea3, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xb5233f3e, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0x7b8c3a36, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xc08b36a5, __VMLINUX_SYMBOL_STR(ata_std_prereset) },
	{ 0xf7f542c9, __VMLINUX_SYMBOL_STR(ata_port_wait_eh) },
	{ 0x65e75cb6, __VMLINUX_SYMBOL_STR(__list_del_entry) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xf9a482f9, __VMLINUX_SYMBOL_STR(msleep) },
	{ 0xa2b43768, __VMLINUX_SYMBOL_STR(scsi_change_queue_depth) },
	{ 0x16b7094d, __VMLINUX_SYMBOL_STR(sas_remove_children) },
	{ 0x112e8668, __VMLINUX_SYMBOL_STR(sas_release_transport) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0x6c09c2a4, __VMLINUX_SYMBOL_STR(del_timer) },
	{ 0x89cf4c4a, __VMLINUX_SYMBOL_STR(page_address) },
	{ 0x9ea8ad06, __VMLINUX_SYMBOL_STR(blk_abort_request) },
	{ 0x30fad32e, __VMLINUX_SYMBOL_STR(scsi_block_requests) },
	{ 0xfb55f0af, __VMLINUX_SYMBOL_STR(ata_std_sched_eh) },
	{ 0xc8b57c27, __VMLINUX_SYMBOL_STR(autoremove_wake_function) },
	{ 0xe36464b0, __VMLINUX_SYMBOL_STR(sas_port_free) },
	{ 0xd8bdde0b, __VMLINUX_SYMBOL_STR(dev_printk) },
	{ 0xa23696f9, __VMLINUX_SYMBOL_STR(sas_phy_add) },
	{ 0x9c65e0c0, __VMLINUX_SYMBOL_STR(scsi_unblock_requests) },
	{ 0x660e3b9f, __VMLINUX_SYMBOL_STR(ata_sas_slave_configure) },
	{ 0xa9d1586, __VMLINUX_SYMBOL_STR(ata_scsi_cmd_error_handler) },
	{ 0xf707b91c, __VMLINUX_SYMBOL_STR(sas_port_add_phy) },
	{ 0xe094ef39, __VMLINUX_SYMBOL_STR(sg_next) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0x27dae810, __VMLINUX_SYMBOL_STR(sas_rphy_free) },
	{ 0x9580deb, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x62b72b0d, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0xd482c0da, __VMLINUX_SYMBOL_STR(sas_port_delete_phy) },
	{ 0xc9a0581d, __VMLINUX_SYMBOL_STR(sas_rphy_add) },
	{ 0xef65ea5, __VMLINUX_SYMBOL_STR(ata_sas_port_suspend) },
	{ 0x5a1faad9, __VMLINUX_SYMBOL_STR(ata_sas_port_init) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x343a1a8, __VMLINUX_SYMBOL_STR(__list_add) },
	{ 0xc82bea03, __VMLINUX_SYMBOL_STR(sas_port_delete) },
	{ 0x4d6ff32f, __VMLINUX_SYMBOL_STR(ata_sas_async_probe) },
	{ 0x63b87fc5, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0xb7616588, __VMLINUX_SYMBOL_STR(sas_attach_transport) },
	{ 0xd49bd803, __VMLINUX_SYMBOL_STR(wait_for_completion) },
	{ 0xd1a5deac, __VMLINUX_SYMBOL_STR(kmap_atomic) },
	{ 0xbb152ef3, __VMLINUX_SYMBOL_STR(scsi_is_host_device) },
	{ 0x9f894e93, __VMLINUX_SYMBOL_STR(sas_rphy_delete) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0x706c5a65, __VMLINUX_SYMBOL_STR(preempt_count_sub) },
	{ 0xbb0722c3, __VMLINUX_SYMBOL_STR(ata_sas_port_stop) },
	{ 0x1a3c31ac, __VMLINUX_SYMBOL_STR(scsi_queue_work) },
	{ 0x403f0154, __VMLINUX_SYMBOL_STR(sas_expander_alloc) },
	{ 0x11089ac7, __VMLINUX_SYMBOL_STR(_ctype) },
	{ 0x79984e17, __VMLINUX_SYMBOL_STR(sas_read_port_mode_page) },
	{ 0x48a0f939, __VMLINUX_SYMBOL_STR(mutex_lock_interruptible) },
	{ 0xe97fa8af, __VMLINUX_SYMBOL_STR(sas_end_device_alloc) },
	{ 0xdc798d37, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x71c90087, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x5f58a9fe, __VMLINUX_SYMBOL_STR(ata_std_error_handler) },
	{ 0xc3fe47c9, __VMLINUX_SYMBOL_STR(ata_scsi_port_error_handler) },
	{ 0x943ed822, __VMLINUX_SYMBOL_STR(ata_sas_port_start) },
	{ 0xe19231e2, __VMLINUX_SYMBOL_STR(ata_std_qc_defer) },
	{ 0xf4b6cdae, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0xf70afe2a, __VMLINUX_SYMBOL_STR(sas_port_mark_backlink) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xe16b893b, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xed93f29e, __VMLINUX_SYMBOL_STR(__kunmap_atomic) },
	{ 0xd384def7, __VMLINUX_SYMBOL_STR(sas_port_add) },
	{ 0x521445b, __VMLINUX_SYMBOL_STR(list_del) },
	{ 0x1bb31047, __VMLINUX_SYMBOL_STR(add_timer) },
	{ 0x43b0c9c3, __VMLINUX_SYMBOL_STR(preempt_schedule) },
	{ 0xf811e69d, __VMLINUX_SYMBOL_STR(scsi_eh_flush_done_q) },
	{ 0x7c344093, __VMLINUX_SYMBOL_STR(ata_port_schedule_eh) },
	{ 0xb1c0c1c2, __VMLINUX_SYMBOL_STR(async_schedule_domain) },
	{ 0x6d521587, __VMLINUX_SYMBOL_STR(ata_sas_port_alloc) },
	{ 0x91d581ec, __VMLINUX_SYMBOL_STR(ata_noop_qc_prep) },
	{ 0x99cd26eb, __VMLINUX_SYMBOL_STR(scsi_eh_finish_cmd) },
	{ 0x61aa416f, __VMLINUX_SYMBOL_STR(sas_phy_free) },
	{ 0xc9e4f0cb, __VMLINUX_SYMBOL_STR(_dev_info) },
	{ 0x55184b5d, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x73c832f2, __VMLINUX_SYMBOL_STR(ata_dev_classify) },
	{ 0x7c8e67a0, __VMLINUX_SYMBOL_STR(put_device) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x6cd21997, __VMLINUX_SYMBOL_STR(ata_tf_to_fis) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0x314d034e, __VMLINUX_SYMBOL_STR(sas_phy_alloc) },
	{ 0xe8c74318, __VMLINUX_SYMBOL_STR(ata_wait_after_reset) },
	{ 0xcaa1a2be, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xc7da6011, __VMLINUX_SYMBOL_STR(__dynamic_dev_dbg) },
	{ 0xd9ff3ac3, __VMLINUX_SYMBOL_STR(get_device) },
	{ 0x71aa3ade, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0x26c90ea4, __VMLINUX_SYMBOL_STR(scsi_eh_get_sense) },
	{ 0xb9e52429, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x158f2f00, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0x822137e2, __VMLINUX_SYMBOL_STR(arm_heavy_mb) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0x82701365, __VMLINUX_SYMBOL_STR(int_to_scsilun) },
	{ 0x5c265cba, __VMLINUX_SYMBOL_STR(sg_init_one) },
	{ 0x99e84898, __VMLINUX_SYMBOL_STR(ata_sas_port_resume) },
	{ 0xd2b6e981, __VMLINUX_SYMBOL_STR(sas_port_get_phy) },
	{ 0x9c55cec, __VMLINUX_SYMBOL_STR(schedule_timeout_interruptible) },
	{ 0x50f13dd2, __VMLINUX_SYMBOL_STR(scsi_eh_ready_devs) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x6ca4bf88, __VMLINUX_SYMBOL_STR(async_synchronize_full_domain) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x9304b6, __VMLINUX_SYMBOL_STR(ata_tf_from_fis) },
	{ 0x75a17bed, __VMLINUX_SYMBOL_STR(prepare_to_wait) },
	{ 0xd38f37eb, __VMLINUX_SYMBOL_STR(sas_port_alloc) },
	{ 0x38fd2110, __VMLINUX_SYMBOL_STR(ata_host_init) },
	{ 0xd4ba991b, __VMLINUX_SYMBOL_STR(flush_kernel_dcache_page) },
	{ 0x5ed56e18, __VMLINUX_SYMBOL_STR(request_firmware) },
	{ 0xf13e906c, __VMLINUX_SYMBOL_STR(scsi_schedule_eh) },
	{ 0x8893fa5d, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0xf9dd9922, __VMLINUX_SYMBOL_STR(__init_swait_queue_head) },
	{ 0x2f0664db, __VMLINUX_SYMBOL_STR(dev_warn) },
	{ 0xee813ae5, __VMLINUX_SYMBOL_STR(ata_std_postreset) },
	{ 0xefd6cf06, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr0) },
	{ 0x8f678b07, __VMLINUX_SYMBOL_STR(__stack_chk_guard) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0xe07bae1d, __VMLINUX_SYMBOL_STR(sas_rphy_unlink) },
	{ 0x9cbcaf26, __VMLINUX_SYMBOL_STR(complete) },
	{ 0xca54fee, __VMLINUX_SYMBOL_STR(_test_and_set_bit) },
	{ 0x13d1073d, __VMLINUX_SYMBOL_STR(ata_sas_queuecmd) },
	{ 0xe2ad9518, __VMLINUX_SYMBOL_STR(ata_sas_port_destroy) },
	{ 0xa38602cd, __VMLINUX_SYMBOL_STR(drain_workqueue) },
	{ 0xf229424a, __VMLINUX_SYMBOL_STR(preempt_count_add) },
	{ 0x9358ffd, __VMLINUX_SYMBOL_STR(sas_rphy_remove) },
	{ 0x22ef151f, __VMLINUX_SYMBOL_STR(release_firmware) },
	{ 0xfc3fb221, __VMLINUX_SYMBOL_STR(ata_sas_scsi_ioctl) },
	{ 0xa61e25dd, __VMLINUX_SYMBOL_STR(__ata_change_queue_depth) },
	{ 0x9b1635c0, __VMLINUX_SYMBOL_STR(ata_qc_complete) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=scsi_transport_sas";

