#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x2c197ea3, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x92b57248, __VMLINUX_SYMBOL_STR(flush_work) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0x1b3a1f0c, __VMLINUX_SYMBOL_STR(drm_gem_prime_export) },
	{ 0x79afd04, __VMLINUX_SYMBOL_STR(drm_release) },
	{ 0xd3b20d70, __VMLINUX_SYMBOL_STR(drm_fb_helper_set_par) },
	{ 0x6bbb1537, __VMLINUX_SYMBOL_STR(ttm_pool_populate) },
	{ 0x7b8c3a36, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xccf6a318, __VMLINUX_SYMBOL_STR(ttm_dma_tt_init) },
	{ 0x5760c0d2, __VMLINUX_SYMBOL_STR(drm_dev_register) },
	{ 0x370c0f03, __VMLINUX_SYMBOL_STR(drm_atomic_helper_update_plane) },
	{ 0xe73d945f, __VMLINUX_SYMBOL_STR(drm_atomic_helper_crtc_duplicate_state) },
	{ 0x189c3a74, __VMLINUX_SYMBOL_STR(mem_map) },
	{ 0x89e0ce7b, __VMLINUX_SYMBOL_STR(drm_dev_alloc) },
	{ 0x686ebf07, __VMLINUX_SYMBOL_STR(drm_fb_helper_initial_config) },
	{ 0x7aa1756e, __VMLINUX_SYMBOL_STR(kvfree) },
	{ 0x7e42e836, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0x97255bdf, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x179c312a, __VMLINUX_SYMBOL_STR(drm_mode_config_cleanup) },
	{ 0x838e5e27, __VMLINUX_SYMBOL_STR(drm_mode_config_reset) },
	{ 0x5c23a979, __VMLINUX_SYMBOL_STR(drm_atomic_helper_connector_reset) },
	{ 0xf1f650f0, __VMLINUX_SYMBOL_STR(drm_set_preferred_mode) },
	{ 0x224b69db, __VMLINUX_SYMBOL_STR(ttm_bo_validate) },
	{ 0x8dd8459c, __VMLINUX_SYMBOL_STR(ttm_bo_init) },
	{ 0xc8d8f5c6, __VMLINUX_SYMBOL_STR(drm_fb_helper_debug_leave) },
	{ 0xa7f87f2f, __VMLINUX_SYMBOL_STR(drm_cvt_mode) },
	{ 0x5fb20428, __VMLINUX_SYMBOL_STR(virtio_check_driver_offered_feature) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0x4055a3, __VMLINUX_SYMBOL_STR(get_task_comm) },
	{ 0xe6657df, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x346127a7, __VMLINUX_SYMBOL_STR(drm_global_item_ref) },
	{ 0x25c03974, __VMLINUX_SYMBOL_STR(fence_default_wait) },
	{ 0xe094ef39, __VMLINUX_SYMBOL_STR(sg_next) },
	{ 0x987c11c7, __VMLINUX_SYMBOL_STR(__pv_phys_pfn_offset) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0x9580deb, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x28cc25db, __VMLINUX_SYMBOL_STR(arm_copy_from_user) },
	{ 0x4d5cf86e, __VMLINUX_SYMBOL_STR(drm_kms_helper_hotplug_event) },
	{ 0x62b72b0d, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x7327ac5e, __VMLINUX_SYMBOL_STR(virtqueue_kick) },
	{ 0xbed09bf2, __VMLINUX_SYMBOL_STR(drm_dev_unref) },
	{ 0x3dbaf91c, __VMLINUX_SYMBOL_STR(drm_encoder_init) },
	{ 0x852e2efa, __VMLINUX_SYMBOL_STR(drm_atomic_helper_crtc_reset) },
	{ 0x45b7dfae, __VMLINUX_SYMBOL_STR(drm_universal_plane_init) },
	{ 0x8fbeb765, __VMLINUX_SYMBOL_STR(virtqueue_get_buf) },
	{ 0x343a1a8, __VMLINUX_SYMBOL_STR(__list_add) },
	{ 0x6670c2e6, __VMLINUX_SYMBOL_STR(drm_connector_cleanup) },
	{ 0xf4fa543b, __VMLINUX_SYMBOL_STR(arm_copy_to_user) },
	{ 0xbf1faebe, __VMLINUX_SYMBOL_STR(mutex_trylock) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0xdd8ec340, __VMLINUX_SYMBOL_STR(drm_fb_helper_unregister_fbi) },
	{ 0x78c6bf1c, __VMLINUX_SYMBOL_STR(drm_atomic_helper_connector_duplicate_state) },
	{ 0x63b87fc5, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0xd5310d2c, __VMLINUX_SYMBOL_STR(drm_fb_helper_pan_display) },
	{ 0xd45c2f25, __VMLINUX_SYMBOL_STR(ttm_mem_global_init) },
	{ 0x9da77c70, __VMLINUX_SYMBOL_STR(drm_atomic_helper_set_config) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0x5f754e5a, __VMLINUX_SYMBOL_STR(memset) },
	{ 0x304a5016, __VMLINUX_SYMBOL_STR(ttm_mem_global_release) },
	{ 0xf8151173, __VMLINUX_SYMBOL_STR(drm_mode_connector_attach_encoder) },
	{ 0xbf5dc6cf, __VMLINUX_SYMBOL_STR(ttm_bo_unref) },
	{ 0x429be6d3, __VMLINUX_SYMBOL_STR(remove_conflicting_framebuffers) },
	{ 0x706c5a65, __VMLINUX_SYMBOL_STR(preempt_count_sub) },
	{ 0x79cf82fd, __VMLINUX_SYMBOL_STR(virtqueue_add_sgs) },
	{ 0xef1e4705, __VMLINUX_SYMBOL_STR(dev_err) },
	{ 0x5b86d54f, __VMLINUX_SYMBOL_STR(ttm_bo_add_to_lru) },
	{ 0x48a0f939, __VMLINUX_SYMBOL_STR(mutex_lock_interruptible) },
	{ 0x69e1b606, __VMLINUX_SYMBOL_STR(drm_helper_mode_fill_fb_struct) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x78461197, __VMLINUX_SYMBOL_STR(drm_crtc_init_with_planes) },
	{ 0xec0b4e7e, __VMLINUX_SYMBOL_STR(drm_put_dev) },
	{ 0xa8d9df63, __VMLINUX_SYMBOL_STR(drm_atomic_helper_plane_reset) },
	{ 0x2b8614fe, __VMLINUX_SYMBOL_STR(drm_gem_handle_create) },
	{ 0xbbdf3975, __VMLINUX_SYMBOL_STR(ttm_bo_kmap) },
	{ 0x4a4beab0, __VMLINUX_SYMBOL_STR(drm_fb_helper_fill_var) },
	{ 0x328a05f1, __VMLINUX_SYMBOL_STR(strncpy) },
	{ 0xc7d30250, __VMLINUX_SYMBOL_STR(virtqueue_disable_cb) },
	{ 0x70b95ac3, __VMLINUX_SYMBOL_STR(drm_send_vblank_event) },
	{ 0x4d3c5ea, __VMLINUX_SYMBOL_STR(ttm_eu_fence_buffer_objects) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xe16b893b, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x84ffea8b, __VMLINUX_SYMBOL_STR(idr_preload) },
	{ 0x521445b, __VMLINUX_SYMBOL_STR(list_del) },
	{ 0xce85ad30, __VMLINUX_SYMBOL_STR(drm_gem_object_release) },
	{ 0x4fca41b6, __VMLINUX_SYMBOL_STR(drm_read) },
	{ 0x3bfa482e, __VMLINUX_SYMBOL_STR(ttm_bo_dma_acc_size) },
	{ 0xa634b079, __VMLINUX_SYMBOL_STR(noop_llseek) },
	{ 0x46c7ef01, __VMLINUX_SYMBOL_STR(ttm_bo_init_mm) },
	{ 0x6d2bde6f, __VMLINUX_SYMBOL_STR(ttm_bo_wait) },
	{ 0x8bfd8946, __VMLINUX_SYMBOL_STR(idr_alloc) },
	{ 0xa17fa8a1, __VMLINUX_SYMBOL_STR(ttm_bo_device_init) },
	{ 0x43b0c9c3, __VMLINUX_SYMBOL_STR(preempt_schedule) },
	{ 0xf6d8b256, __VMLINUX_SYMBOL_STR(drm_fb_helper_release_fbi) },
	{ 0x60644041, __VMLINUX_SYMBOL_STR(drm_debugfs_create_files) },
	{ 0x1dd71f7a, __VMLINUX_SYMBOL_STR(drm_err) },
	{ 0xc691a923, __VMLINUX_SYMBOL_STR(drm_connector_init) },
	{ 0x94eb12dc, __VMLINUX_SYMBOL_STR(drm_fb_helper_prepare) },
	{ 0x4c0745bf, __VMLINUX_SYMBOL_STR(idr_remove) },
	{ 0x20645642, __VMLINUX_SYMBOL_STR(drm_debug) },
	{ 0xefe6429a, __VMLINUX_SYMBOL_STR(fence_signal_locked) },
	{ 0x4ea1f5a2, __VMLINUX_SYMBOL_STR(drm_gem_object_free) },
	{ 0x7cde8988, __VMLINUX_SYMBOL_STR(ttm_eu_backoff_reservation) },
	{ 0x20060f72, __VMLINUX_SYMBOL_STR(virtqueue_get_vring_size) },
	{ 0x98764398, __VMLINUX_SYMBOL_STR(drm_gem_prime_fd_to_handle) },
	{ 0xcd27ea0c, __VMLINUX_SYMBOL_STR(drm_ioctl) },
	{ 0xad12615, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_imageblit) },
	{ 0x8ac11c1a, __VMLINUX_SYMBOL_STR(drm_gem_prime_import) },
	{ 0xea412576, __VMLINUX_SYMBOL_STR(drm_atomic_helper_plane_duplicate_state) },
	{ 0xd5f61212, __VMLINUX_SYMBOL_STR(drm_atomic_helper_connector_destroy_state) },
	{ 0xae64b44b, __VMLINUX_SYMBOL_STR(unregister_virtio_driver) },
	{ 0x2c9500f4, __VMLINUX_SYMBOL_STR(drm_atomic_helper_check) },
	{ 0xb04cdfe4, __VMLINUX_SYMBOL_STR(ttm_bo_del_sub_from_lru) },
	{ 0x575d7e1c, __VMLINUX_SYMBOL_STR(drm_atomic_helper_commit) },
	{ 0x3f616ce2, __VMLINUX_SYMBOL_STR(queue_delayed_work_on) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0xa8127191, __VMLINUX_SYMBOL_STR(drm_fb_helper_check_var) },
	{ 0x59aa14cf, __VMLINUX_SYMBOL_STR(fence_release) },
	{ 0x2ecf3d84, __VMLINUX_SYMBOL_STR(drm_fb_helper_blank) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0x704aec8a, __VMLINUX_SYMBOL_STR(drm_gem_object_lookup) },
	{ 0xfdbb30cf, __VMLINUX_SYMBOL_STR(drm_gem_handle_delete) },
	{ 0x587eaac1, __VMLINUX_SYMBOL_STR(drm_add_modes_noedid) },
	{ 0xc42a84fc, __VMLINUX_SYMBOL_STR(ttm_eu_reserve_buffers) },
	{ 0xcaa1a2be, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x4b55b70e, __VMLINUX_SYMBOL_STR(drm_fb_helper_alloc_fbi) },
	{ 0x4d40fc15, __VMLINUX_SYMBOL_STR(reservation_object_add_excl_fence) },
	{ 0x148e0ff7, __VMLINUX_SYMBOL_STR(drm_atomic_helper_connector_dpms) },
	{ 0x742780b8, __VMLINUX_SYMBOL_STR(drm_gem_prime_handle_to_fd) },
	{ 0xb9e52429, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x5b271d57, __VMLINUX_SYMBOL_STR(drm_connector_unregister) },
	{ 0x931cc7d1, __VMLINUX_SYMBOL_STR(drm_gem_object_init) },
	{ 0xec71a48b, __VMLINUX_SYMBOL_STR(drm_encoder_cleanup) },
	{ 0x158f2f00, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0xe27dbb01, __VMLINUX_SYMBOL_STR(ttm_bo_device_release) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0x6c4f834a, __VMLINUX_SYMBOL_STR(drm_crtc_cleanup) },
	{ 0x5c265cba, __VMLINUX_SYMBOL_STR(sg_init_one) },
	{ 0x28d6861d, __VMLINUX_SYMBOL_STR(__vmalloc) },
	{ 0x7ac7dbe1, __VMLINUX_SYMBOL_STR(drm_atomic_helper_crtc_destroy_state) },
	{ 0x2861542e, __VMLINUX_SYMBOL_STR(drm_mode_config_init) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xeb41b10b, __VMLINUX_SYMBOL_STR(ttm_dma_tt_fini) },
	{ 0xe6690dc2, __VMLINUX_SYMBOL_STR(drm_helper_hpd_irq_event) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x8e1308b1, __VMLINUX_SYMBOL_STR(ww_mutex_unlock) },
	{ 0x1db7dc40, __VMLINUX_SYMBOL_STR(pgprot_kernel) },
	{ 0x2bfe933c, __VMLINUX_SYMBOL_STR(sg_alloc_table_from_pages) },
	{ 0xa0f869e, __VMLINUX_SYMBOL_STR(drm_debugfs_remove_files) },
	{ 0xbe77b741, __VMLINUX_SYMBOL_STR(drm_fb_helper_fini) },
	{ 0x8893fa5d, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0xffdb82bc, __VMLINUX_SYMBOL_STR(sg_free_table) },
	{ 0xefd6cf06, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr0) },
	{ 0xba744892, __VMLINUX_SYMBOL_STR(drm_atomic_helper_disable_plane) },
	{ 0x8f678b07, __VMLINUX_SYMBOL_STR(__stack_chk_guard) },
	{ 0xba1c8731, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_fillrect) },
	{ 0x5cf59609, __VMLINUX_SYMBOL_STR(ttm_bo_global_init) },
	{ 0xc6dc78a7, __VMLINUX_SYMBOL_STR(drm_mode_probed_add) },
	{ 0xb2d48a2e, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0xb81960ca, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0xb73ea1d6, __VMLINUX_SYMBOL_STR(drm_fb_helper_setcmap) },
	{ 0xb0c7e431, __VMLINUX_SYMBOL_STR(drm_framebuffer_init) },
	{ 0x19361835, __VMLINUX_SYMBOL_STR(fence_init) },
	{ 0xc360e7e2, __VMLINUX_SYMBOL_STR(drm_ut_debug_printk) },
	{ 0xcdb41bcf, __VMLINUX_SYMBOL_STR(idr_init) },
	{ 0xf229424a, __VMLINUX_SYMBOL_STR(preempt_count_add) },
	{ 0x8f7b2492, __VMLINUX_SYMBOL_STR(ttm_pool_unpopulate) },
	{ 0x4e973fa5, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_copyarea) },
	{ 0x5a22e144, __VMLINUX_SYMBOL_STR(drm_fb_helper_fill_fix) },
	{ 0xf3a91734, __VMLINUX_SYMBOL_STR(drm_connector_register) },
	{ 0x3ac1fef9, __VMLINUX_SYMBOL_STR(drm_mode_legacy_fb_format) },
	{ 0x2130fe1, __VMLINUX_SYMBOL_STR(drm_helper_probe_single_connector_modes_nomerge) },
	{ 0x7de37172, __VMLINUX_SYMBOL_STR(virtqueue_enable_cb) },
	{ 0x83f9115c, __VMLINUX_SYMBOL_STR(drm_mode_crtc_set_gamma_size) },
	{ 0x67b1d568, __VMLINUX_SYMBOL_STR(ttm_bo_global_release) },
	{ 0xf6009f4d, __VMLINUX_SYMBOL_STR(drm_fb_helper_debug_enter) },
	{ 0x839bab53, __VMLINUX_SYMBOL_STR(drm_poll) },
	{ 0xa4e3749, __VMLINUX_SYMBOL_STR(drm_fb_helper_init) },
	{ 0x340142cb, __VMLINUX_SYMBOL_STR(drm_fb_helper_single_add_all_connectors) },
	{ 0xf245fc47, __VMLINUX_SYMBOL_STR(drm_open) },
	{ 0xfccafb1, __VMLINUX_SYMBOL_STR(drm_global_item_unref) },
	{ 0x671ee67e, __VMLINUX_SYMBOL_STR(drm_atomic_helper_plane_destroy_state) },
	{ 0x703a13f8, __VMLINUX_SYMBOL_STR(register_virtio_driver) },
	{ 0x8a66910, __VMLINUX_SYMBOL_STR(drm_framebuffer_cleanup) },
	{ 0x905cdaff, __VMLINUX_SYMBOL_STR(ttm_bo_mmap) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=ttm";

MODULE_ALIAS("virtio:d00000010v*");
