#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x9cef51a8, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x38807165, __VMLINUX_SYMBOL_STR(vfs_create) },
	{ 0xa23ca842, __VMLINUX_SYMBOL_STR(set_create_files_as) },
	{ 0x10ab577b, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0xf6789fdc, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x65e75cb6, __VMLINUX_SYMBOL_STR(__list_del_entry) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x405c1144, __VMLINUX_SYMBOL_STR(get_seconds) },
	{ 0xde289da7, __VMLINUX_SYMBOL_STR(set_security_override_from_ctx) },
	{ 0x9ffeb3cb, __VMLINUX_SYMBOL_STR(security_path_rename) },
	{ 0xbae14f5, __VMLINUX_SYMBOL_STR(security_inode_mkdir) },
	{ 0x55913380, __VMLINUX_SYMBOL_STR(up_read) },
	{ 0x5fc56a46, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0x349cba85, __VMLINUX_SYMBOL_STR(strchr) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0xa0fbac79, __VMLINUX_SYMBOL_STR(wake_up_bit) },
	{ 0x97255bdf, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0xa5d3ef3f, __VMLINUX_SYMBOL_STR(fscache_object_mark_killed) },
	{ 0x6260af68, __VMLINUX_SYMBOL_STR(prepare_kernel_cred) },
	{ 0x6f0ee77e, __VMLINUX_SYMBOL_STR(dget_parent) },
	{ 0xc8b57c27, __VMLINUX_SYMBOL_STR(autoremove_wake_function) },
	{ 0xc72f6987, __VMLINUX_SYMBOL_STR(pagecache_get_page) },
	{ 0xb5198b77, __VMLINUX_SYMBOL_STR(_raw_read_lock) },
	{ 0x20000329, __VMLINUX_SYMBOL_STR(simple_strtoul) },
	{ 0x7f4bc430, __VMLINUX_SYMBOL_STR(touch_atime) },
	{ 0xcdc49e19, __VMLINUX_SYMBOL_STR(lockref_get) },
	{ 0xf4b90401, __VMLINUX_SYMBOL_STR(dput) },
	{ 0x2a3aa678, __VMLINUX_SYMBOL_STR(_test_and_clear_bit) },
	{ 0x8cf640d5, __VMLINUX_SYMBOL_STR(dentry_open) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0x97106714, __VMLINUX_SYMBOL_STR(memdup_user_nul) },
	{ 0xfc6e022, __VMLINUX_SYMBOL_STR(add_to_page_cache_lru) },
	{ 0x7d0db255, __VMLINUX_SYMBOL_STR(fscache_object_init) },
	{ 0xdbe8baac, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0xf63c6381, __VMLINUX_SYMBOL_STR(fscache_object_lookup_negative) },
	{ 0x248defae, __VMLINUX_SYMBOL_STR(path_get) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0xec92f732, __VMLINUX_SYMBOL_STR(fscache_add_cache) },
	{ 0x88fdd4a9, __VMLINUX_SYMBOL_STR(fscache_check_aux) },
	{ 0x464e8348, __VMLINUX_SYMBOL_STR(override_creds) },
	{ 0xddfee4dd, __VMLINUX_SYMBOL_STR(__alloc_pages_nodemask) },
	{ 0x3e8cc412, __VMLINUX_SYMBOL_STR(security_inode_create) },
	{ 0xc499ae1e, __VMLINUX_SYMBOL_STR(kstrdup) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x343a1a8, __VMLINUX_SYMBOL_STR(__list_add) },
	{ 0x6a7d611a, __VMLINUX_SYMBOL_STR(security_path_unlink) },
	{ 0xf4fa543b, __VMLINUX_SYMBOL_STR(arm_copy_to_user) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0xadbfbef8, __VMLINUX_SYMBOL_STR(down_read) },
	{ 0xc120bb45, __VMLINUX_SYMBOL_STR(unlock_rename) },
	{ 0x25631afd, __VMLINUX_SYMBOL_STR(fscache_cache_cleared_wq) },
	{ 0x275ef902, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x49163ab3, __VMLINUX_SYMBOL_STR(kmap_atomic) },
	{ 0x20a6fc5b, __VMLINUX_SYMBOL_STR(misc_register) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0xc01dfb0a, __VMLINUX_SYMBOL_STR(kern_path) },
	{ 0x8627019e, __VMLINUX_SYMBOL_STR(security_path_mkdir) },
	{ 0x11089ac7, __VMLINUX_SYMBOL_STR(_ctype) },
	{ 0x5a32f871, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x6093de76, __VMLINUX_SYMBOL_STR(fscache_obtained_object) },
	{ 0xdfd61436, __VMLINUX_SYMBOL_STR(_raw_write_unlock) },
	{ 0x4bc9fa80, __VMLINUX_SYMBOL_STR(_raw_read_unlock) },
	{ 0xbcff3d85, __VMLINUX_SYMBOL_STR(kunmap) },
	{ 0xf9dc2bec, __VMLINUX_SYMBOL_STR(vfs_getxattr) },
	{ 0x4d9b652b, __VMLINUX_SYMBOL_STR(rb_erase) },
	{ 0x1a1431fd, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irq) },
	{ 0xd26e0e90, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0xd6c0da7f, __VMLINUX_SYMBOL_STR(lock_rename) },
	{ 0xfed0a669, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xd100acbd, __VMLINUX_SYMBOL_STR(_raw_write_lock) },
	{ 0xed93f29e, __VMLINUX_SYMBOL_STR(__kunmap_atomic) },
	{ 0x521445b, __VMLINUX_SYMBOL_STR(list_del) },
	{ 0xd9e5aeb6, __VMLINUX_SYMBOL_STR(noop_llseek) },
	{ 0xef77a998, __VMLINUX_SYMBOL_STR(fscache_withdraw_cache) },
	{ 0xdd27fa87, __VMLINUX_SYMBOL_STR(memchr) },
	{ 0xbeed5ae8, __VMLINUX_SYMBOL_STR(unlock_page) },
	{ 0x229b20b2, __VMLINUX_SYMBOL_STR(up_write) },
	{ 0x7cbdf731, __VMLINUX_SYMBOL_STR(down_write) },
	{ 0x33ff49a8, __VMLINUX_SYMBOL_STR(fput) },
	{ 0x1e3d9a1b, __VMLINUX_SYMBOL_STR(fscache_mark_pages_cached) },
	{ 0x672d3170, __VMLINUX_SYMBOL_STR(fscache_mark_page_cached) },
	{ 0xf69ee7fe, __VMLINUX_SYMBOL_STR(contig_page_data) },
	{ 0xbc169a9d, __VMLINUX_SYMBOL_STR(prepare_creds) },
	{ 0xa1f0ebea, __VMLINUX_SYMBOL_STR(bit_waitqueue) },
	{ 0x632780, __VMLINUX_SYMBOL_STR(work_busy) },
	{ 0xa3848753, __VMLINUX_SYMBOL_STR(mntput) },
	{ 0x783b3563, __VMLINUX_SYMBOL_STR(wake_up_atomic_t) },
	{ 0xc6cbbc89, __VMLINUX_SYMBOL_STR(capable) },
	{ 0x666774aa, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x4d0d163d, __VMLINUX_SYMBOL_STR(copy_page) },
	{ 0x2d41e8fa, __VMLINUX_SYMBOL_STR(kmap) },
	{ 0x92a7b445, __VMLINUX_SYMBOL_STR(fscache_init_cache) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x448808c8, __VMLINUX_SYMBOL_STR(fscache_object_destroy) },
	{ 0x3507a132, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irq) },
	{ 0xfc2634fc, __VMLINUX_SYMBOL_STR(vfs_statfs) },
	{ 0x6d7468ea, __VMLINUX_SYMBOL_STR(vfs_mkdir) },
	{ 0x5b7b8673, __VMLINUX_SYMBOL_STR(__put_cred) },
	{ 0x23249c8d, __VMLINUX_SYMBOL_STR(path_put) },
	{ 0x187b8d19, __VMLINUX_SYMBOL_STR(vfs_truncate) },
	{ 0x147fb690, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x9056088, __VMLINUX_SYMBOL_STR(security_path_mknod) },
	{ 0x2fd712dd, __VMLINUX_SYMBOL_STR(fscache_put_operation) },
	{ 0xa5526619, __VMLINUX_SYMBOL_STR(rb_insert_color) },
	{ 0x577e866f, __VMLINUX_SYMBOL_STR(vfs_unlink) },
	{ 0xedf65a89, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0xd85cd67e, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x9a09d2fa, __VMLINUX_SYMBOL_STR(add_page_wait_queue) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x499cb58c, __VMLINUX_SYMBOL_STR(prepare_to_wait) },
	{ 0x721b1851, __VMLINUX_SYMBOL_STR(skip_spaces) },
	{ 0x7940b12d, __VMLINUX_SYMBOL_STR(sync_filesystem) },
	{ 0xbf4ced89, __VMLINUX_SYMBOL_STR(fscache_io_error) },
	{ 0x9980bf47, __VMLINUX_SYMBOL_STR(abort_creds) },
	{ 0xa2fb4090, __VMLINUX_SYMBOL_STR(__kernel_write) },
	{ 0x1cfb04fa, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x8f678b07, __VMLINUX_SYMBOL_STR(__stack_chk_guard) },
	{ 0x92cf98e, __VMLINUX_SYMBOL_STR(fscache_object_sleep_till_congested) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0xb81960ca, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0xca54fee, __VMLINUX_SYMBOL_STR(_test_and_set_bit) },
	{ 0x1569f9b1, __VMLINUX_SYMBOL_STR(fscache_enqueue_operation) },
	{ 0xaeb0a446, __VMLINUX_SYMBOL_STR(lookup_one_len) },
	{ 0x684bf5af, __VMLINUX_SYMBOL_STR(vfs_rename) },
	{ 0x49ebacbd, __VMLINUX_SYMBOL_STR(_clear_bit) },
	{ 0x8154b0fb, __VMLINUX_SYMBOL_STR(fscache_object_retrying_stale) },
	{ 0x19edc693, __VMLINUX_SYMBOL_STR(fscache_op_complete) },
	{ 0x23fa4443, __VMLINUX_SYMBOL_STR(param_ops_uint) },
	{ 0x64ee57c8, __VMLINUX_SYMBOL_STR(notify_change) },
	{ 0x1ef27cc6, __VMLINUX_SYMBOL_STR(vfs_setxattr) },
	{ 0xc163e689, __VMLINUX_SYMBOL_STR(misc_deregister) },
	{ 0xe37805d2, __VMLINUX_SYMBOL_STR(revert_creds) },
	{ 0x2ef3e65f, __VMLINUX_SYMBOL_STR(__put_page) },
	{ 0x85908c25, __VMLINUX_SYMBOL_STR(vfs_removexattr) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=fscache";

