#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x2c197ea3, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x8a95576a, __VMLINUX_SYMBOL_STR(vfs_create) },
	{ 0x30b2fc30, __VMLINUX_SYMBOL_STR(set_create_files_as) },
	{ 0xb5233f3e, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0x7b8c3a36, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x65e75cb6, __VMLINUX_SYMBOL_STR(__list_del_entry) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x405c1144, __VMLINUX_SYMBOL_STR(get_seconds) },
	{ 0x6fcf03a, __VMLINUX_SYMBOL_STR(set_security_override_from_ctx) },
	{ 0x2eca2915, __VMLINUX_SYMBOL_STR(security_path_rename) },
	{ 0x682bbcd0, __VMLINUX_SYMBOL_STR(security_inode_mkdir) },
	{ 0x26c06d6c, __VMLINUX_SYMBOL_STR(up_read) },
	{ 0x349cba85, __VMLINUX_SYMBOL_STR(strchr) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0xa0fbac79, __VMLINUX_SYMBOL_STR(wake_up_bit) },
	{ 0x97255bdf, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x25b8160, __VMLINUX_SYMBOL_STR(fscache_object_mark_killed) },
	{ 0x99094eaa, __VMLINUX_SYMBOL_STR(prepare_kernel_cred) },
	{ 0x71c769c9, __VMLINUX_SYMBOL_STR(dget_parent) },
	{ 0xc8b57c27, __VMLINUX_SYMBOL_STR(autoremove_wake_function) },
	{ 0xe88aed1e, __VMLINUX_SYMBOL_STR(pagecache_get_page) },
	{ 0x20000329, __VMLINUX_SYMBOL_STR(simple_strtoul) },
	{ 0xc1729d2f, __VMLINUX_SYMBOL_STR(touch_atime) },
	{ 0x5dd81c4f, __VMLINUX_SYMBOL_STR(lockref_get) },
	{ 0xe7fcc45d, __VMLINUX_SYMBOL_STR(dput) },
	{ 0x1f1bec6f, __VMLINUX_SYMBOL_STR(dentry_open) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0x28cc25db, __VMLINUX_SYMBOL_STR(arm_copy_from_user) },
	{ 0x8ed65a9a, __VMLINUX_SYMBOL_STR(add_to_page_cache_lru) },
	{ 0x6d62be1a, __VMLINUX_SYMBOL_STR(fscache_object_init) },
	{ 0x62b72b0d, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x2e0cf5a6, __VMLINUX_SYMBOL_STR(fscache_object_lookup_negative) },
	{ 0xa383cf01, __VMLINUX_SYMBOL_STR(path_get) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0x2516793, __VMLINUX_SYMBOL_STR(fscache_add_cache) },
	{ 0xd81a71a7, __VMLINUX_SYMBOL_STR(fscache_check_aux) },
	{ 0x8591edc9, __VMLINUX_SYMBOL_STR(override_creds) },
	{ 0x492621b9, __VMLINUX_SYMBOL_STR(__alloc_pages_nodemask) },
	{ 0x1ef70e2, __VMLINUX_SYMBOL_STR(security_inode_create) },
	{ 0xc499ae1e, __VMLINUX_SYMBOL_STR(kstrdup) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x343a1a8, __VMLINUX_SYMBOL_STR(__list_add) },
	{ 0x11291b8, __VMLINUX_SYMBOL_STR(security_path_unlink) },
	{ 0xf4fa543b, __VMLINUX_SYMBOL_STR(arm_copy_to_user) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0x9101360b, __VMLINUX_SYMBOL_STR(down_read) },
	{ 0x76f6fbea, __VMLINUX_SYMBOL_STR(unlock_rename) },
	{ 0x394c16e9, __VMLINUX_SYMBOL_STR(fscache_cache_cleared_wq) },
	{ 0x63b87fc5, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0xd1a5deac, __VMLINUX_SYMBOL_STR(kmap_atomic) },
	{ 0xa01ec12f, __VMLINUX_SYMBOL_STR(misc_register) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0xb366b85b, __VMLINUX_SYMBOL_STR(kern_path) },
	{ 0x706c5a65, __VMLINUX_SYMBOL_STR(preempt_count_sub) },
	{ 0xc5ed1330, __VMLINUX_SYMBOL_STR(security_path_mkdir) },
	{ 0x11089ac7, __VMLINUX_SYMBOL_STR(_ctype) },
	{ 0xdc798d37, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x39f0dd7b, __VMLINUX_SYMBOL_STR(fscache_obtained_object) },
	{ 0x82bf6794, __VMLINUX_SYMBOL_STR(kunmap) },
	{ 0xf54c1003, __VMLINUX_SYMBOL_STR(vfs_getxattr) },
	{ 0xa1c76e0a, __VMLINUX_SYMBOL_STR(_cond_resched) },
	{ 0x4d9b652b, __VMLINUX_SYMBOL_STR(rb_erase) },
	{ 0xf4b6cdae, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x8fa4752e, __VMLINUX_SYMBOL_STR(lock_rename) },
	{ 0xe16b893b, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xed93f29e, __VMLINUX_SYMBOL_STR(__kunmap_atomic) },
	{ 0x521445b, __VMLINUX_SYMBOL_STR(list_del) },
	{ 0xa634b079, __VMLINUX_SYMBOL_STR(noop_llseek) },
	{ 0xf6eab89f, __VMLINUX_SYMBOL_STR(fscache_withdraw_cache) },
	{ 0xdd27fa87, __VMLINUX_SYMBOL_STR(memchr) },
	{ 0x43b0c9c3, __VMLINUX_SYMBOL_STR(preempt_schedule) },
	{ 0x9c318af3, __VMLINUX_SYMBOL_STR(unlock_page) },
	{ 0x394fd24c, __VMLINUX_SYMBOL_STR(fput) },
	{ 0x3e061b94, __VMLINUX_SYMBOL_STR(__get_page_tail) },
	{ 0x8a53ec1a, __VMLINUX_SYMBOL_STR(fscache_mark_pages_cached) },
	{ 0x82f384ea, __VMLINUX_SYMBOL_STR(fscache_mark_page_cached) },
	{ 0x6ae0f10b, __VMLINUX_SYMBOL_STR(contig_page_data) },
	{ 0xda8d36c, __VMLINUX_SYMBOL_STR(prepare_creds) },
	{ 0xcd4b732f, __VMLINUX_SYMBOL_STR(bit_waitqueue) },
	{ 0x632780, __VMLINUX_SYMBOL_STR(work_busy) },
	{ 0xedf1c1d7, __VMLINUX_SYMBOL_STR(mntput) },
	{ 0x783b3563, __VMLINUX_SYMBOL_STR(wake_up_atomic_t) },
	{ 0xc6cbbc89, __VMLINUX_SYMBOL_STR(capable) },
	{ 0x55184b5d, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x4d0d163d, __VMLINUX_SYMBOL_STR(copy_page) },
	{ 0xd50d26aa, __VMLINUX_SYMBOL_STR(kmap) },
	{ 0x6f606644, __VMLINUX_SYMBOL_STR(fscache_init_cache) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0xe288f847, __VMLINUX_SYMBOL_STR(fscache_object_destroy) },
	{ 0xcb8e71fb, __VMLINUX_SYMBOL_STR(vfs_statfs) },
	{ 0xdfbceb42, __VMLINUX_SYMBOL_STR(vfs_mkdir) },
	{ 0x644c6df7, __VMLINUX_SYMBOL_STR(__put_cred) },
	{ 0x108cc112, __VMLINUX_SYMBOL_STR(path_put) },
	{ 0xc23a7a9f, __VMLINUX_SYMBOL_STR(vfs_truncate) },
	{ 0xcaa1a2be, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x97e7c468, __VMLINUX_SYMBOL_STR(security_path_mknod) },
	{ 0x3bcec2a, __VMLINUX_SYMBOL_STR(fscache_put_operation) },
	{ 0xa5526619, __VMLINUX_SYMBOL_STR(rb_insert_color) },
	{ 0x41204a36, __VMLINUX_SYMBOL_STR(vfs_unlink) },
	{ 0x71aa3ade, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0xb9e52429, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0xa3886cb9, __VMLINUX_SYMBOL_STR(add_page_wait_queue) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x75a17bed, __VMLINUX_SYMBOL_STR(prepare_to_wait) },
	{ 0x721b1851, __VMLINUX_SYMBOL_STR(skip_spaces) },
	{ 0xdccedf00, __VMLINUX_SYMBOL_STR(sync_filesystem) },
	{ 0xb0683064, __VMLINUX_SYMBOL_STR(fscache_io_error) },
	{ 0xe1cc9f61, __VMLINUX_SYMBOL_STR(abort_creds) },
	{ 0x4d265394, __VMLINUX_SYMBOL_STR(put_page) },
	{ 0x44ecfa98, __VMLINUX_SYMBOL_STR(__kernel_write) },
	{ 0x8893fa5d, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0xefd6cf06, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr0) },
	{ 0x8f678b07, __VMLINUX_SYMBOL_STR(__stack_chk_guard) },
	{ 0x92cf98e, __VMLINUX_SYMBOL_STR(fscache_object_sleep_till_congested) },
	{ 0xb81960ca, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0xe280c50b, __VMLINUX_SYMBOL_STR(fscache_enqueue_operation) },
	{ 0x4c3c0238, __VMLINUX_SYMBOL_STR(lookup_one_len) },
	{ 0xc34359eb, __VMLINUX_SYMBOL_STR(vfs_rename) },
	{ 0xf229424a, __VMLINUX_SYMBOL_STR(preempt_count_add) },
	{ 0x8cedf74d, __VMLINUX_SYMBOL_STR(fscache_object_retrying_stale) },
	{ 0x560c2bd0, __VMLINUX_SYMBOL_STR(fscache_op_complete) },
	{ 0xd109e4f8, __VMLINUX_SYMBOL_STR(param_ops_uint) },
	{ 0x3e001b70, __VMLINUX_SYMBOL_STR(notify_change) },
	{ 0x287cc937, __VMLINUX_SYMBOL_STR(vfs_setxattr) },
	{ 0xf8e4433c, __VMLINUX_SYMBOL_STR(misc_deregister) },
	{ 0x80b1e704, __VMLINUX_SYMBOL_STR(revert_creds) },
	{ 0xffbb9217, __VMLINUX_SYMBOL_STR(vfs_removexattr) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=fscache";

