#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x2c197ea3, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x61b7b126, __VMLINUX_SYMBOL_STR(simple_strtoull) },
	{ 0x615ee1ed, __VMLINUX_SYMBOL_STR(kobject_put) },
	{ 0x4e01994e, __VMLINUX_SYMBOL_STR(kset_create_and_add) },
	{ 0x2824f024, __VMLINUX_SYMBOL_STR(ore_get_io_state) },
	{ 0xb5233f3e, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0x54884034, __VMLINUX_SYMBOL_STR(iget_failed) },
	{ 0x7b8c3a36, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xbe5cd90e, __VMLINUX_SYMBOL_STR(drop_nlink) },
	{ 0x769c083f, __VMLINUX_SYMBOL_STR(osduld_device_same) },
	{ 0x9404cae6, __VMLINUX_SYMBOL_STR(generic_file_llseek) },
	{ 0xa76b61a5, __VMLINUX_SYMBOL_STR(ore_read) },
	{ 0x2720d984, __VMLINUX_SYMBOL_STR(__mark_inode_dirty) },
	{ 0x1637726c, __VMLINUX_SYMBOL_STR(__set_page_dirty_nobuffers) },
	{ 0x83ace46e, __VMLINUX_SYMBOL_STR(extract_attr_from_ios) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0x97255bdf, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x60a13e90, __VMLINUX_SYMBOL_STR(rcu_barrier) },
	{ 0x89cf4c4a, __VMLINUX_SYMBOL_STR(page_address) },
	{ 0xc7e82cf2, __VMLINUX_SYMBOL_STR(filemap_write_and_wait_range) },
	{ 0xc17edb1, __VMLINUX_SYMBOL_STR(osd_sec_init_nosec_doall_caps) },
	{ 0xdac7b009, __VMLINUX_SYMBOL_STR(simple_write_end) },
	{ 0xb1993f6, __VMLINUX_SYMBOL_STR(generic_fh_to_parent) },
	{ 0x79aa04a2, __VMLINUX_SYMBOL_STR(get_random_bytes) },
	{ 0x1ef96291, __VMLINUX_SYMBOL_STR(is_bad_inode) },
	{ 0xe88aed1e, __VMLINUX_SYMBOL_STR(pagecache_get_page) },
	{ 0x619dfd50, __VMLINUX_SYMBOL_STR(generic_file_open) },
	{ 0xacf4d843, __VMLINUX_SYMBOL_STR(match_strdup) },
	{ 0x428166d6, __VMLINUX_SYMBOL_STR(__lock_page) },
	{ 0xf7802486, __VMLINUX_SYMBOL_STR(__aeabi_uidivmod) },
	{ 0xce8f27e0, __VMLINUX_SYMBOL_STR(osd_req_read_kern) },
	{ 0xe7fcc45d, __VMLINUX_SYMBOL_STR(dput) },
	{ 0x44e9a829, __VMLINUX_SYMBOL_STR(match_token) },
	{ 0x17396551, __VMLINUX_SYMBOL_STR(inc_nlink) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0x55cf3589, __VMLINUX_SYMBOL_STR(init_user_ns) },
	{ 0xfb859678, __VMLINUX_SYMBOL_STR(osduld_path_lookup) },
	{ 0x62b72b0d, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x85df9b6c, __VMLINUX_SYMBOL_STR(strsep) },
	{ 0x75e2edae, __VMLINUX_SYMBOL_STR(vfs_fsync) },
	{ 0x23021130, __VMLINUX_SYMBOL_STR(ore_put_io_state) },
	{ 0x17c466cb, __VMLINUX_SYMBOL_STR(page_symlink_inode_operations) },
	{ 0xdc76b57f, __VMLINUX_SYMBOL_STR(generic_read_dir) },
	{ 0x28aa6a67, __VMLINUX_SYMBOL_STR(call_rcu) },
	{ 0xbfdcfeb8, __VMLINUX_SYMBOL_STR(mount_nodev) },
	{ 0xcebf34e5, __VMLINUX_SYMBOL_STR(set_page_dirty) },
	{ 0x64df141, __VMLINUX_SYMBOL_STR(ore_write) },
	{ 0x88fc8474, __VMLINUX_SYMBOL_STR(truncate_setsize) },
	{ 0xd7c8a4c5, __VMLINUX_SYMBOL_STR(end_page_writeback) },
	{ 0x64c5538b, __VMLINUX_SYMBOL_STR(make_kgid) },
	{ 0x63b87fc5, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0xc2c8c8e8, __VMLINUX_SYMBOL_STR(osduld_info_lookup) },
	{ 0xe707d823, __VMLINUX_SYMBOL_STR(__aeabi_uidiv) },
	{ 0x52e07b4f, __VMLINUX_SYMBOL_STR(__insert_inode_hash) },
	{ 0x7a2add7d, __VMLINUX_SYMBOL_STR(current_kernel_time64) },
	{ 0xd1a5deac, __VMLINUX_SYMBOL_STR(kmap_atomic) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0x5f754e5a, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xf4d89728, __VMLINUX_SYMBOL_STR(from_kuid) },
	{ 0x706c5a65, __VMLINUX_SYMBOL_STR(preempt_count_sub) },
	{ 0x4577f530, __VMLINUX_SYMBOL_STR(simple_write_begin) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x3a87fec2, __VMLINUX_SYMBOL_STR(d_obtain_alias) },
	{ 0x71c90087, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x71dbcfd0, __VMLINUX_SYMBOL_STR(kobject_init_and_add) },
	{ 0xf8789e0, __VMLINUX_SYMBOL_STR(ore_check_io) },
	{ 0x82bf6794, __VMLINUX_SYMBOL_STR(kunmap) },
	{ 0x328a05f1, __VMLINUX_SYMBOL_STR(strncpy) },
	{ 0x2544b63d, __VMLINUX_SYMBOL_STR(from_kgid) },
	{ 0xf4b6cdae, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x76478707, __VMLINUX_SYMBOL_STR(set_nlink) },
	{ 0xe16b893b, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x6bfe11b5, __VMLINUX_SYMBOL_STR(write_cache_pages) },
	{ 0xed93f29e, __VMLINUX_SYMBOL_STR(__kunmap_atomic) },
	{ 0x5203c6bf, __VMLINUX_SYMBOL_STR(osd_finalize_request) },
	{ 0x9ec0a1e7, __VMLINUX_SYMBOL_STR(setattr_copy) },
	{ 0xfa4689ad, __VMLINUX_SYMBOL_STR(page_symlink) },
	{ 0xe4bf70b8, __VMLINUX_SYMBOL_STR(truncate_pagecache) },
	{ 0x4e3567f7, __VMLINUX_SYMBOL_STR(match_int) },
	{ 0xfe237bcf, __VMLINUX_SYMBOL_STR(simple_symlink_inode_operations) },
	{ 0x43b0c9c3, __VMLINUX_SYMBOL_STR(preempt_schedule) },
	{ 0x9c318af3, __VMLINUX_SYMBOL_STR(unlock_page) },
	{ 0x2b9d3f01, __VMLINUX_SYMBOL_STR(generic_file_read_iter) },
	{ 0x28806871, __VMLINUX_SYMBOL_STR(ore_verify_layout) },
	{ 0x520e923b, __VMLINUX_SYMBOL_STR(inode_init_once) },
	{ 0x55184b5d, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x6d957e85, __VMLINUX_SYMBOL_STR(generic_file_mmap) },
	{ 0xd50d26aa, __VMLINUX_SYMBOL_STR(kmap) },
	{ 0x5b835dd2, __VMLINUX_SYMBOL_STR(fs_kobj) },
	{ 0x14a7dc3e, __VMLINUX_SYMBOL_STR(truncate_inode_pages_final) },
	{ 0xca65c2f4, __VMLINUX_SYMBOL_STR(make_kuid) },
	{ 0x273befb1, __VMLINUX_SYMBOL_STR(osduld_put_device) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x5523720c, __VMLINUX_SYMBOL_STR(osd_start_request) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x60f632bc, __VMLINUX_SYMBOL_STR(osd_end_request) },
	{ 0x22feb4ba, __VMLINUX_SYMBOL_STR(unlock_new_inode) },
	{ 0xdd39a461, __VMLINUX_SYMBOL_STR(empty_zero_page) },
	{ 0xf159c05, __VMLINUX_SYMBOL_STR(bdi_setup_and_register) },
	{ 0x5faffa5e, __VMLINUX_SYMBOL_STR(inode_change_ok) },
	{ 0xcaa1a2be, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x462a2e75, __VMLINUX_SYMBOL_STR(match_strlcpy) },
	{ 0xfab5b5c, __VMLINUX_SYMBOL_STR(read_cache_pages) },
	{ 0xab667612, __VMLINUX_SYMBOL_STR(sync_inode_metadata) },
	{ 0x71aa3ade, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0x46701a7, __VMLINUX_SYMBOL_STR(register_filesystem) },
	{ 0xb9e52429, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x46c824f6, __VMLINUX_SYMBOL_STR(generic_file_write_iter) },
	{ 0x158f2f00, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0xbbdc3042, __VMLINUX_SYMBOL_STR(__test_set_page_writeback) },
	{ 0x467b4a3e, __VMLINUX_SYMBOL_STR(iter_file_splice_write) },
	{ 0x562fead2, __VMLINUX_SYMBOL_STR(kset_unregister) },
	{ 0x89dfe9fd, __VMLINUX_SYMBOL_STR(ore_get_rw_state) },
	{ 0xde158532, __VMLINUX_SYMBOL_STR(iput) },
	{ 0x9e2985d0, __VMLINUX_SYMBOL_STR(read_cache_page) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xd890ab08, __VMLINUX_SYMBOL_STR(ihold) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xb086b7e5, __VMLINUX_SYMBOL_STR(d_splice_alias) },
	{ 0x7d4bdaa5, __VMLINUX_SYMBOL_STR(ore_create) },
	{ 0x4d265394, __VMLINUX_SYMBOL_STR(put_page) },
	{ 0xeef79882, __VMLINUX_SYMBOL_STR(d_make_root) },
	{ 0x8893fa5d, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x62fb4eda, __VMLINUX_SYMBOL_STR(bdi_destroy) },
	{ 0x2aadd6e5, __VMLINUX_SYMBOL_STR(unregister_filesystem) },
	{ 0xc2346577, __VMLINUX_SYMBOL_STR(ore_truncate) },
	{ 0x2b287b0, __VMLINUX_SYMBOL_STR(write_one_page) },
	{ 0x714b2312, __VMLINUX_SYMBOL_STR(init_special_inode) },
	{ 0xefd6cf06, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr0) },
	{ 0x8f678b07, __VMLINUX_SYMBOL_STR(__stack_chk_guard) },
	{ 0x65ccfa54, __VMLINUX_SYMBOL_STR(ore_remove) },
	{ 0xb81960ca, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0x7fc085f3, __VMLINUX_SYMBOL_STR(new_inode) },
	{ 0x19bd8907, __VMLINUX_SYMBOL_STR(generic_file_splice_read) },
	{ 0xf229424a, __VMLINUX_SYMBOL_STR(preempt_count_add) },
	{ 0xab7febcf, __VMLINUX_SYMBOL_STR(generic_fh_to_dentry) },
	{ 0x918ee80f, __VMLINUX_SYMBOL_STR(osduld_device_info) },
	{ 0xefe1b74e, __VMLINUX_SYMBOL_STR(clear_inode) },
	{ 0xceaa752d, __VMLINUX_SYMBOL_STR(d_instantiate) },
	{ 0x3f7b410a, __VMLINUX_SYMBOL_STR(osd_execute_request) },
	{ 0xb9a1aebe, __VMLINUX_SYMBOL_STR(flush_dcache_page) },
	{ 0x5916d7fb, __VMLINUX_SYMBOL_STR(iget_locked) },
	{ 0xb859f38b, __VMLINUX_SYMBOL_STR(krealloc) },
	{ 0xe5bbba02, __VMLINUX_SYMBOL_STR(inode_init_owner) },
	{ 0xa1fc5ed, __VMLINUX_SYMBOL_STR(generic_shutdown_super) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=libore,osd,libosd";

