#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x9cef51a8, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x601dac66, __VMLINUX_SYMBOL_STR(drm_release) },
	{ 0x28dc2d00, __VMLINUX_SYMBOL_STR(drm_prime_gem_destroy) },
	{ 0x66fa3ca5, __VMLINUX_SYMBOL_STR(drm_fb_helper_set_par) },
	{ 0xf6789fdc, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x65e75cb6, __VMLINUX_SYMBOL_STR(__list_del_entry) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x413cfe42, __VMLINUX_SYMBOL_STR(drm_crtc_helper_set_config) },
	{ 0x12d56c22, __VMLINUX_SYMBOL_STR(drm_dev_register) },
	{ 0x31e1fda7, __VMLINUX_SYMBOL_STR(drm_gem_put_pages) },
	{ 0xb1f11cda, __VMLINUX_SYMBOL_STR(drm_dev_alloc) },
	{ 0x921ea593, __VMLINUX_SYMBOL_STR(drm_fb_helper_initial_config) },
	{ 0x7aa1756e, __VMLINUX_SYMBOL_STR(kvfree) },
	{ 0xefe21d65, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0x292db41e, __VMLINUX_SYMBOL_STR(page_address) },
	{ 0xc6c6a41, __VMLINUX_SYMBOL_STR(drm_gem_dmabuf_release) },
	{ 0x7b30d359, __VMLINUX_SYMBOL_STR(drm_mode_config_cleanup) },
	{ 0xd26ca2c8, __VMLINUX_SYMBOL_STR(drm_unplug_dev) },
	{ 0xbdb5f786, __VMLINUX_SYMBOL_STR(arm_dma_ops) },
	{ 0x364132a6, __VMLINUX_SYMBOL_STR(drm_fb_helper_unlink_fbi) },
	{ 0xf36454f1, __VMLINUX_SYMBOL_STR(dma_buf_detach) },
	{ 0x365c8ef2, __VMLINUX_SYMBOL_STR(drm_fb_helper_debug_leave) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0x1afae5e7, __VMLINUX_SYMBOL_STR(down_interruptible) },
	{ 0xaf6d6978, __VMLINUX_SYMBOL_STR(drm_helper_probe_single_connector_modes) },
	{ 0xe2fae716, __VMLINUX_SYMBOL_STR(kmemdup) },
	{ 0xd5152710, __VMLINUX_SYMBOL_STR(sg_next) },
	{ 0xfed87e5e, __VMLINUX_SYMBOL_STR(drm_gem_free_mmap_offset) },
	{ 0x3106eeb, __VMLINUX_SYMBOL_STR(drm_vblank_cleanup) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0x8fdf772a, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0xdbe8baac, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x7e2ade76, __VMLINUX_SYMBOL_STR(drm_dev_unref) },
	{ 0xe503dd2d, __VMLINUX_SYMBOL_STR(drm_vblank_init) },
	{ 0xd00f9404, __VMLINUX_SYMBOL_STR(drm_encoder_init) },
	{ 0xf76b0a59, __VMLINUX_SYMBOL_STR(read_current_timer) },
	{ 0x343a1a8, __VMLINUX_SYMBOL_STR(__list_add) },
	{ 0x645de547, __VMLINUX_SYMBOL_STR(drm_connector_cleanup) },
	{ 0x83eb06ea, __VMLINUX_SYMBOL_STR(drm_fb_helper_unregister_fbi) },
	{ 0xb927a92b, __VMLINUX_SYMBOL_STR(dma_buf_vunmap) },
	{ 0x8696db7f, __VMLINUX_SYMBOL_STR(usb_get_descriptor) },
	{ 0xbde639aa, __VMLINUX_SYMBOL_STR(drm_fb_helper_pan_display) },
	{ 0xe707d823, __VMLINUX_SYMBOL_STR(__aeabi_uidiv) },
	{ 0xf6109673, __VMLINUX_SYMBOL_STR(drm_helper_connector_dpms) },
	{ 0x5f754e5a, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xd0d31103, __VMLINUX_SYMBOL_STR(drm_mode_connector_attach_encoder) },
	{ 0x3744cf36, __VMLINUX_SYMBOL_STR(vmalloc_to_pfn) },
	{ 0x51d559d1, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0xa14e5fee, __VMLINUX_SYMBOL_STR(drm_prime_pages_to_sg) },
	{ 0x1a329efe, __VMLINUX_SYMBOL_STR(usb_deregister) },
	{ 0xa30f39d6, __VMLINUX_SYMBOL_STR(drm_gem_object_unreference_unlocked) },
	{ 0xf9a9ffb3, __VMLINUX_SYMBOL_STR(drm_helper_mode_fill_fb_struct) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xd3c91e1b, __VMLINUX_SYMBOL_STR(drm_gem_handle_create) },
	{ 0x5f191d5, __VMLINUX_SYMBOL_STR(drm_gem_dumb_destroy) },
	{ 0x48eeabcc, __VMLINUX_SYMBOL_STR(vmap) },
	{ 0xdbfbac54, __VMLINUX_SYMBOL_STR(dma_buf_put) },
	{ 0xcd64a356, __VMLINUX_SYMBOL_STR(drm_fb_helper_fill_var) },
	{ 0xfacd2e14, __VMLINUX_SYMBOL_STR(pgprot_user) },
	{ 0x82fc1495, __VMLINUX_SYMBOL_STR(usb_control_msg) },
	{ 0xfed0a669, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xfdb032c8, __VMLINUX_SYMBOL_STR(drm_gem_object_release) },
	{ 0x75a5306d, __VMLINUX_SYMBOL_STR(drm_read) },
	{ 0xd9e5aeb6, __VMLINUX_SYMBOL_STR(noop_llseek) },
	{ 0xf69b9380, __VMLINUX_SYMBOL_STR(drm_add_edid_modes) },
	{ 0x8177fceb, __VMLINUX_SYMBOL_STR(drm_fb_helper_release_fbi) },
	{ 0x7e3061cb, __VMLINUX_SYMBOL_STR(dma_buf_unmap_attachment) },
	{ 0xe47cb9b4, __VMLINUX_SYMBOL_STR(usb_free_coherent) },
	{ 0x483b21ab, __VMLINUX_SYMBOL_STR(drm_connector_init) },
	{ 0x2196324, __VMLINUX_SYMBOL_STR(__aeabi_idiv) },
	{ 0x67047d2f, __VMLINUX_SYMBOL_STR(drm_fb_helper_prepare) },
	{ 0x945ef453, __VMLINUX_SYMBOL_STR(drm_gem_vm_open) },
	{ 0x15b8211, __VMLINUX_SYMBOL_STR(drm_mode_connector_update_edid_property) },
	{ 0xadffb84, __VMLINUX_SYMBOL_STR(vm_insert_page) },
	{ 0xd2fab0a1, __VMLINUX_SYMBOL_STR(drm_gem_vm_close) },
	{ 0xcdd158d, __VMLINUX_SYMBOL_STR(sg_alloc_table) },
	{ 0x5b425c35, __VMLINUX_SYMBOL_STR(drm_gem_prime_fd_to_handle) },
	{ 0xcae9ad1c, __VMLINUX_SYMBOL_STR(dma_buf_begin_cpu_access) },
	{ 0xf3207539, __VMLINUX_SYMBOL_STR(drm_printk) },
	{ 0x16f69619, __VMLINUX_SYMBOL_STR(drm_ioctl) },
	{ 0xb9e2cb, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_imageblit) },
	{ 0x7500da19, __VMLINUX_SYMBOL_STR(usb_submit_urb) },
	{ 0x78b578a1, __VMLINUX_SYMBOL_STR(drm_gem_mmap) },
	{ 0x69f55758, __VMLINUX_SYMBOL_STR(dma_buf_map_attachment) },
	{ 0x98a0bc05, __VMLINUX_SYMBOL_STR(drm_gem_dmabuf_export) },
	{ 0x7d4eb58b, __VMLINUX_SYMBOL_STR(drm_framebuffer_unregister_private) },
	{ 0xf8dfe3ad, __VMLINUX_SYMBOL_STR(put_device) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x8ac0717e, __VMLINUX_SYMBOL_STR(drm_fb_helper_check_var) },
	{ 0x72d44692, __VMLINUX_SYMBOL_STR(drm_fb_helper_blank) },
	{ 0xd7f70bf5, __VMLINUX_SYMBOL_STR(drm_crtc_send_vblank_event) },
	{ 0x69cc7108, __VMLINUX_SYMBOL_STR(drm_gem_object_lookup) },
	{ 0x147fb690, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xd575b730, __VMLINUX_SYMBOL_STR(drm_fb_helper_alloc_fbi) },
	{ 0x10649205, __VMLINUX_SYMBOL_STR(drm_crtc_init) },
	{ 0x598542b2, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0xaf1c96a5, __VMLINUX_SYMBOL_STR(dma_buf_attach) },
	{ 0xd45ca525, __VMLINUX_SYMBOL_STR(drm_gem_prime_handle_to_fd) },
	{ 0x657b2089, __VMLINUX_SYMBOL_STR(get_device) },
	{ 0x2b737f8f, __VMLINUX_SYMBOL_STR(drm_connector_unregister) },
	{ 0x2e30b5ba, __VMLINUX_SYMBOL_STR(drm_gem_object_init) },
	{ 0x4f22c747, __VMLINUX_SYMBOL_STR(drm_encoder_cleanup) },
	{ 0xca7c725d, __VMLINUX_SYMBOL_STR(fb_deferred_io_cleanup) },
	{ 0x89771ce3, __VMLINUX_SYMBOL_STR(fb_deferred_io_init) },
	{ 0xab29d79f, __VMLINUX_SYMBOL_STR(drm_gem_create_mmap_offset) },
	{ 0x88199286, __VMLINUX_SYMBOL_STR(drm_crtc_cleanup) },
	{ 0x28d6861d, __VMLINUX_SYMBOL_STR(__vmalloc) },
	{ 0x451692cb, __VMLINUX_SYMBOL_STR(drm_mode_config_init) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x94961283, __VMLINUX_SYMBOL_STR(vunmap) },
	{ 0x8d6feec3, __VMLINUX_SYMBOL_STR(remap_pfn_range) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x1ea78ac7, __VMLINUX_SYMBOL_STR(drm_fb_helper_deferred_io) },
	{ 0x4828fb49, __VMLINUX_SYMBOL_STR(drm_gem_object_unreference) },
	{ 0x4be7fb63, __VMLINUX_SYMBOL_STR(up) },
	{ 0x60fad71b, __VMLINUX_SYMBOL_STR(usb_register_driver) },
	{ 0x1db7dc40, __VMLINUX_SYMBOL_STR(pgprot_kernel) },
	{ 0x241a061f, __VMLINUX_SYMBOL_STR(drm_fb_helper_fini) },
	{ 0x165a8081, __VMLINUX_SYMBOL_STR(drm_modeset_lock_all) },
	{ 0x9cd60539, __VMLINUX_SYMBOL_STR(sg_free_table) },
	{ 0x3e884f4b, __VMLINUX_SYMBOL_STR(vm_get_page_prot) },
	{ 0x6e13c7da, __VMLINUX_SYMBOL_STR(drm_prime_sg_to_page_addr_arrays) },
	{ 0x8f678b07, __VMLINUX_SYMBOL_STR(__stack_chk_guard) },
	{ 0x543b7d6f, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_fillrect) },
	{ 0xa70b5042, __VMLINUX_SYMBOL_STR(drm_modeset_unlock_all) },
	{ 0x125bc872, __VMLINUX_SYMBOL_STR(drm_helper_disable_unused_functions) },
	{ 0x91f0bbb8, __VMLINUX_SYMBOL_STR(dma_buf_end_cpu_access) },
	{ 0x1c063098, __VMLINUX_SYMBOL_STR(drm_fb_helper_setcmap) },
	{ 0x570b43fe, __VMLINUX_SYMBOL_STR(usb_alloc_coherent) },
	{ 0x2f37dd29, __VMLINUX_SYMBOL_STR(drm_framebuffer_init) },
	{ 0x481a3861, __VMLINUX_SYMBOL_STR(dma_buf_vmap) },
	{ 0x73502a13, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_copyarea) },
	{ 0x2143094b, __VMLINUX_SYMBOL_STR(drm_gem_get_pages) },
	{ 0x3b5d91d3, __VMLINUX_SYMBOL_STR(drm_fb_helper_fill_fix) },
	{ 0xcbf36496, __VMLINUX_SYMBOL_STR(drm_connector_register) },
	{ 0x3ac1fef9, __VMLINUX_SYMBOL_STR(drm_mode_legacy_fb_format) },
	{ 0xa2615298, __VMLINUX_SYMBOL_STR(usb_free_urb) },
	{ 0x837d0f0a, __VMLINUX_SYMBOL_STR(down_timeout) },
	{ 0xe4eb93ba, __VMLINUX_SYMBOL_STR(drm_kms_helper_poll_disable) },
	{ 0x63cc93d2, __VMLINUX_SYMBOL_STR(drm_mode_object_find) },
	{ 0xb035dc98, __VMLINUX_SYMBOL_STR(drm_fb_helper_debug_enter) },
	{ 0xdae73214, __VMLINUX_SYMBOL_STR(drm_poll) },
	{ 0x2a6a5a8e, __VMLINUX_SYMBOL_STR(drm_fb_helper_init) },
	{ 0x63d776f2, __VMLINUX_SYMBOL_STR(drm_fb_helper_single_add_all_connectors) },
	{ 0x4ecc5f3f, __VMLINUX_SYMBOL_STR(usb_alloc_urb) },
	{ 0xd3b5ddf9, __VMLINUX_SYMBOL_STR(drm_open) },
	{ 0xe16024d0, __VMLINUX_SYMBOL_STR(drm_framebuffer_cleanup) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=";

MODULE_ALIAS("usb:v17E9p*d*dc*dsc*dp*icFFisc00ip00in*");
