#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x2c197ea3, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x79afd04, __VMLINUX_SYMBOL_STR(drm_release) },
	{ 0xc51751f6, __VMLINUX_SYMBOL_STR(drm_prime_gem_destroy) },
	{ 0xd3b20d70, __VMLINUX_SYMBOL_STR(drm_fb_helper_set_par) },
	{ 0x7b8c3a36, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x65e75cb6, __VMLINUX_SYMBOL_STR(__list_del_entry) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x313d6eb3, __VMLINUX_SYMBOL_STR(drm_crtc_helper_set_config) },
	{ 0x5760c0d2, __VMLINUX_SYMBOL_STR(drm_dev_register) },
	{ 0x16f538a2, __VMLINUX_SYMBOL_STR(drm_connector_unplug_all) },
	{ 0x273f7f75, __VMLINUX_SYMBOL_STR(drm_gem_put_pages) },
	{ 0x89e0ce7b, __VMLINUX_SYMBOL_STR(drm_dev_alloc) },
	{ 0x686ebf07, __VMLINUX_SYMBOL_STR(drm_fb_helper_initial_config) },
	{ 0x7aa1756e, __VMLINUX_SYMBOL_STR(kvfree) },
	{ 0x7e42e836, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0x89cf4c4a, __VMLINUX_SYMBOL_STR(page_address) },
	{ 0xde675c44, __VMLINUX_SYMBOL_STR(drm_gem_dmabuf_release) },
	{ 0x179c312a, __VMLINUX_SYMBOL_STR(drm_mode_config_cleanup) },
	{ 0x92da3855, __VMLINUX_SYMBOL_STR(drm_unplug_dev) },
	{ 0x6aa005e8, __VMLINUX_SYMBOL_STR(arm_dma_ops) },
	{ 0xab51055d, __VMLINUX_SYMBOL_STR(drm_fb_helper_unlink_fbi) },
	{ 0xb980a61f, __VMLINUX_SYMBOL_STR(dma_buf_detach) },
	{ 0xc8d8f5c6, __VMLINUX_SYMBOL_STR(drm_fb_helper_debug_leave) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0x4fe38dbd, __VMLINUX_SYMBOL_STR(down_interruptible) },
	{ 0xd479fe49, __VMLINUX_SYMBOL_STR(drm_helper_probe_single_connector_modes) },
	{ 0xe094ef39, __VMLINUX_SYMBOL_STR(sg_next) },
	{ 0xc81b4ce5, __VMLINUX_SYMBOL_STR(drm_gem_free_mmap_offset) },
	{ 0xa131add5, __VMLINUX_SYMBOL_STR(drm_vblank_cleanup) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0x9580deb, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x62b72b0d, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0xbed09bf2, __VMLINUX_SYMBOL_STR(drm_dev_unref) },
	{ 0xf751b6da, __VMLINUX_SYMBOL_STR(drm_vblank_init) },
	{ 0x3dbaf91c, __VMLINUX_SYMBOL_STR(drm_encoder_init) },
	{ 0xf76b0a59, __VMLINUX_SYMBOL_STR(read_current_timer) },
	{ 0x343a1a8, __VMLINUX_SYMBOL_STR(__list_add) },
	{ 0x6670c2e6, __VMLINUX_SYMBOL_STR(drm_connector_cleanup) },
	{ 0xdd8ec340, __VMLINUX_SYMBOL_STR(drm_fb_helper_unregister_fbi) },
	{ 0x94dd61df, __VMLINUX_SYMBOL_STR(dma_buf_vunmap) },
	{ 0x3ee00664, __VMLINUX_SYMBOL_STR(usb_get_descriptor) },
	{ 0xd5310d2c, __VMLINUX_SYMBOL_STR(drm_fb_helper_pan_display) },
	{ 0xe707d823, __VMLINUX_SYMBOL_STR(__aeabi_uidiv) },
	{ 0x2d170fe1, __VMLINUX_SYMBOL_STR(drm_helper_connector_dpms) },
	{ 0x5f754e5a, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xf8151173, __VMLINUX_SYMBOL_STR(drm_mode_connector_attach_encoder) },
	{ 0x706c5a65, __VMLINUX_SYMBOL_STR(preempt_count_sub) },
	{ 0x3744cf36, __VMLINUX_SYMBOL_STR(vmalloc_to_pfn) },
	{ 0xfa6b86cf, __VMLINUX_SYMBOL_STR(drm_prime_pages_to_sg) },
	{ 0x76d817, __VMLINUX_SYMBOL_STR(usb_deregister) },
	{ 0x69e1b606, __VMLINUX_SYMBOL_STR(drm_helper_mode_fill_fb_struct) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x717c75cb, __VMLINUX_SYMBOL_STR(drm_object_attach_property) },
	{ 0x2b8614fe, __VMLINUX_SYMBOL_STR(drm_gem_handle_create) },
	{ 0x4cb14d8f, __VMLINUX_SYMBOL_STR(drm_gem_dumb_destroy) },
	{ 0x8f16efb1, __VMLINUX_SYMBOL_STR(vmap) },
	{ 0x105e50e1, __VMLINUX_SYMBOL_STR(dma_buf_put) },
	{ 0x4a4beab0, __VMLINUX_SYMBOL_STR(drm_fb_helper_fill_var) },
	{ 0xfacd2e14, __VMLINUX_SYMBOL_STR(pgprot_user) },
	{ 0x94e8602, __VMLINUX_SYMBOL_STR(usb_control_msg) },
	{ 0x70b95ac3, __VMLINUX_SYMBOL_STR(drm_send_vblank_event) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xe16b893b, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xce85ad30, __VMLINUX_SYMBOL_STR(drm_gem_object_release) },
	{ 0x4fca41b6, __VMLINUX_SYMBOL_STR(drm_read) },
	{ 0xa634b079, __VMLINUX_SYMBOL_STR(noop_llseek) },
	{ 0xa36c0176, __VMLINUX_SYMBOL_STR(drm_add_edid_modes) },
	{ 0x43b0c9c3, __VMLINUX_SYMBOL_STR(preempt_schedule) },
	{ 0xf6d8b256, __VMLINUX_SYMBOL_STR(drm_fb_helper_release_fbi) },
	{ 0x520c2a49, __VMLINUX_SYMBOL_STR(dma_buf_unmap_attachment) },
	{ 0x40825f43, __VMLINUX_SYMBOL_STR(usb_free_coherent) },
	{ 0x1dd71f7a, __VMLINUX_SYMBOL_STR(drm_err) },
	{ 0xc691a923, __VMLINUX_SYMBOL_STR(drm_connector_init) },
	{ 0x2196324, __VMLINUX_SYMBOL_STR(__aeabi_idiv) },
	{ 0x94eb12dc, __VMLINUX_SYMBOL_STR(drm_fb_helper_prepare) },
	{ 0xa2cb5dc1, __VMLINUX_SYMBOL_STR(drm_gem_vm_open) },
	{ 0xcba8100d, __VMLINUX_SYMBOL_STR(drm_mode_connector_update_edid_property) },
	{ 0x4adde97d, __VMLINUX_SYMBOL_STR(vm_insert_page) },
	{ 0xdf3fbf78, __VMLINUX_SYMBOL_STR(drm_gem_vm_close) },
	{ 0x20645642, __VMLINUX_SYMBOL_STR(drm_debug) },
	{ 0x4ea1f5a2, __VMLINUX_SYMBOL_STR(drm_gem_object_free) },
	{ 0x9330cb9f, __VMLINUX_SYMBOL_STR(sg_alloc_table) },
	{ 0x98764398, __VMLINUX_SYMBOL_STR(drm_gem_prime_fd_to_handle) },
	{ 0x438dc682, __VMLINUX_SYMBOL_STR(dma_buf_begin_cpu_access) },
	{ 0xcd27ea0c, __VMLINUX_SYMBOL_STR(drm_ioctl) },
	{ 0xad12615, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_imageblit) },
	{ 0xc4ad22c6, __VMLINUX_SYMBOL_STR(usb_submit_urb) },
	{ 0x7c933759, __VMLINUX_SYMBOL_STR(drm_gem_mmap) },
	{ 0x5dede9b1, __VMLINUX_SYMBOL_STR(dma_buf_map_attachment) },
	{ 0xf9c0a008, __VMLINUX_SYMBOL_STR(dma_buf_export) },
	{ 0xcd9b192c, __VMLINUX_SYMBOL_STR(drm_framebuffer_unregister_private) },
	{ 0x7c8e67a0, __VMLINUX_SYMBOL_STR(put_device) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0xa8127191, __VMLINUX_SYMBOL_STR(drm_fb_helper_check_var) },
	{ 0x2ecf3d84, __VMLINUX_SYMBOL_STR(drm_fb_helper_blank) },
	{ 0x704aec8a, __VMLINUX_SYMBOL_STR(drm_gem_object_lookup) },
	{ 0xcaa1a2be, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x4b55b70e, __VMLINUX_SYMBOL_STR(drm_fb_helper_alloc_fbi) },
	{ 0x79fed114, __VMLINUX_SYMBOL_STR(drm_crtc_init) },
	{ 0xd6d00698, __VMLINUX_SYMBOL_STR(dma_buf_attach) },
	{ 0x742780b8, __VMLINUX_SYMBOL_STR(drm_gem_prime_handle_to_fd) },
	{ 0xd9ff3ac3, __VMLINUX_SYMBOL_STR(get_device) },
	{ 0x5b271d57, __VMLINUX_SYMBOL_STR(drm_connector_unregister) },
	{ 0x931cc7d1, __VMLINUX_SYMBOL_STR(drm_gem_object_init) },
	{ 0xec71a48b, __VMLINUX_SYMBOL_STR(drm_encoder_cleanup) },
	{ 0x7edaecef, __VMLINUX_SYMBOL_STR(fb_deferred_io_cleanup) },
	{ 0xac3472b3, __VMLINUX_SYMBOL_STR(fb_deferred_io_init) },
	{ 0xc0f86774, __VMLINUX_SYMBOL_STR(drm_gem_create_mmap_offset) },
	{ 0xfc6dc634, __VMLINUX_SYMBOL_STR(drm_mode_create_dirty_info_property) },
	{ 0x6c4f834a, __VMLINUX_SYMBOL_STR(drm_crtc_cleanup) },
	{ 0x28d6861d, __VMLINUX_SYMBOL_STR(__vmalloc) },
	{ 0x2861542e, __VMLINUX_SYMBOL_STR(drm_mode_config_init) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x94961283, __VMLINUX_SYMBOL_STR(vunmap) },
	{ 0x5f206476, __VMLINUX_SYMBOL_STR(remap_pfn_range) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x364b3fff, __VMLINUX_SYMBOL_STR(up) },
	{ 0x1cd1a26f, __VMLINUX_SYMBOL_STR(usb_register_driver) },
	{ 0x1db7dc40, __VMLINUX_SYMBOL_STR(pgprot_kernel) },
	{ 0xbe77b741, __VMLINUX_SYMBOL_STR(drm_fb_helper_fini) },
	{ 0x4992ca97, __VMLINUX_SYMBOL_STR(drm_modeset_lock_all) },
	{ 0xffdb82bc, __VMLINUX_SYMBOL_STR(sg_free_table) },
	{ 0xefd6cf06, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr0) },
	{ 0x3e884f4b, __VMLINUX_SYMBOL_STR(vm_get_page_prot) },
	{ 0xecbebe98, __VMLINUX_SYMBOL_STR(drm_prime_sg_to_page_addr_arrays) },
	{ 0x8f678b07, __VMLINUX_SYMBOL_STR(__stack_chk_guard) },
	{ 0xba1c8731, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_fillrect) },
	{ 0x8004d4a, __VMLINUX_SYMBOL_STR(drm_modeset_unlock_all) },
	{ 0x1c1cfc1d, __VMLINUX_SYMBOL_STR(drm_helper_disable_unused_functions) },
	{ 0x53cf1975, __VMLINUX_SYMBOL_STR(dma_buf_end_cpu_access) },
	{ 0xb73ea1d6, __VMLINUX_SYMBOL_STR(drm_fb_helper_setcmap) },
	{ 0x7174ae4a, __VMLINUX_SYMBOL_STR(usb_alloc_coherent) },
	{ 0xb0c7e431, __VMLINUX_SYMBOL_STR(drm_framebuffer_init) },
	{ 0xc360e7e2, __VMLINUX_SYMBOL_STR(drm_ut_debug_printk) },
	{ 0xf229424a, __VMLINUX_SYMBOL_STR(preempt_count_add) },
	{ 0xcef81206, __VMLINUX_SYMBOL_STR(dma_buf_vmap) },
	{ 0x4e973fa5, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_copyarea) },
	{ 0x51ca06b3, __VMLINUX_SYMBOL_STR(drm_gem_get_pages) },
	{ 0x5a22e144, __VMLINUX_SYMBOL_STR(drm_fb_helper_fill_fix) },
	{ 0xf3a91734, __VMLINUX_SYMBOL_STR(drm_connector_register) },
	{ 0x3ac1fef9, __VMLINUX_SYMBOL_STR(drm_mode_legacy_fb_format) },
	{ 0x900f303a, __VMLINUX_SYMBOL_STR(usb_free_urb) },
	{ 0xc57877cd, __VMLINUX_SYMBOL_STR(down_timeout) },
	{ 0x5db54bdb, __VMLINUX_SYMBOL_STR(drm_kms_helper_poll_disable) },
	{ 0x657a7037, __VMLINUX_SYMBOL_STR(drm_mode_object_find) },
	{ 0xf6009f4d, __VMLINUX_SYMBOL_STR(drm_fb_helper_debug_enter) },
	{ 0x839bab53, __VMLINUX_SYMBOL_STR(drm_poll) },
	{ 0xa4e3749, __VMLINUX_SYMBOL_STR(drm_fb_helper_init) },
	{ 0x340142cb, __VMLINUX_SYMBOL_STR(drm_fb_helper_single_add_all_connectors) },
	{ 0x55da3d4e, __VMLINUX_SYMBOL_STR(usb_alloc_urb) },
	{ 0xf245fc47, __VMLINUX_SYMBOL_STR(drm_open) },
	{ 0x8a66910, __VMLINUX_SYMBOL_STR(drm_framebuffer_cleanup) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=";

MODULE_ALIAS("usb:v17E9p*d*dc*dsc*dp*icFFisc00ip00in*");
