#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x2c197ea3, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x7e42e836, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0x980382ca, __VMLINUX_SYMBOL_STR(unregister_md_personality) },
	{ 0x8804b529, __VMLINUX_SYMBOL_STR(register_md_personality) },
	{ 0xec39ab7, __VMLINUX_SYMBOL_STR(md_integrity_add_rdev) },
	{ 0x6091797f, __VMLINUX_SYMBOL_STR(synchronize_rcu) },
	{ 0xea8f4a2c, __VMLINUX_SYMBOL_STR(kernfs_notify) },
	{ 0x65e75cb6, __VMLINUX_SYMBOL_STR(__list_del_entry) },
	{ 0x57bc46ab, __VMLINUX_SYMBOL_STR(bio_copy_data) },
	{ 0x71c90087, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x89cf4c4a, __VMLINUX_SYMBOL_STR(page_address) },
	{ 0xbd9074b1, __VMLINUX_SYMBOL_STR(blk_finish_plug) },
	{ 0x63d0363e, __VMLINUX_SYMBOL_STR(submit_bio_wait) },
	{ 0xd2081ff2, __VMLINUX_SYMBOL_STR(bio_alloc_mddev) },
	{ 0xa1c76e0a, __VMLINUX_SYMBOL_STR(_cond_resched) },
	{ 0x4ecb963a, __VMLINUX_SYMBOL_STR(rdev_clear_badblocks) },
	{ 0x521445b, __VMLINUX_SYMBOL_STR(list_del) },
	{ 0x7d705738, __VMLINUX_SYMBOL_STR(blk_start_plug) },
	{ 0x8fa0bc46, __VMLINUX_SYMBOL_STR(md_check_recovery) },
	{ 0x2196324, __VMLINUX_SYMBOL_STR(__aeabi_idiv) },
	{ 0x40913bf, __VMLINUX_SYMBOL_STR(md_error) },
	{ 0x1c589c9b, __VMLINUX_SYMBOL_STR(sync_page_io) },
	{ 0x82bf6794, __VMLINUX_SYMBOL_STR(kunmap) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xd50d26aa, __VMLINUX_SYMBOL_STR(kmap) },
	{ 0xfb159249, __VMLINUX_SYMBOL_STR(md_wait_for_blocked_rdev) },
	{ 0x75a17bed, __VMLINUX_SYMBOL_STR(prepare_to_wait) },
	{ 0x606406d9, __VMLINUX_SYMBOL_STR(flush_signals) },
	{ 0xc8b57c27, __VMLINUX_SYMBOL_STR(autoremove_wake_function) },
	{ 0xd27b25dd, __VMLINUX_SYMBOL_STR(blk_check_plugged) },
	{ 0xdfc8d3cd, __VMLINUX_SYMBOL_STR(bitmap_startwrite) },
	{ 0x27967cbd, __VMLINUX_SYMBOL_STR(bio_trim) },
	{ 0x554c86b4, __VMLINUX_SYMBOL_STR(bio_clone_mddev) },
	{ 0x91469d99, __VMLINUX_SYMBOL_STR(md_write_start) },
	{ 0x2ea452c6, __VMLINUX_SYMBOL_STR(md_done_sync) },
	{ 0xb6bcfdc6, __VMLINUX_SYMBOL_STR(md_unregister_thread) },
	{ 0x4ff23cb8, __VMLINUX_SYMBOL_STR(md_integrity_register) },
	{ 0x357b579b, __VMLINUX_SYMBOL_STR(disk_stack_limits) },
	{ 0x6043e182, __VMLINUX_SYMBOL_STR(blk_queue_max_write_same_sectors) },
	{ 0xe6657df, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x6be960f4, __VMLINUX_SYMBOL_STR(__free_pages) },
	{ 0x190c554f, __VMLINUX_SYMBOL_STR(bio_alloc_pages) },
	{ 0xd397e2e2, __VMLINUX_SYMBOL_STR(bio_alloc_bioset) },
	{ 0x2ad5ec38, __VMLINUX_SYMBOL_STR(bio_add_page) },
	{ 0xbb07c418, __VMLINUX_SYMBOL_STR(bitmap_end_sync) },
	{ 0x11fbf06c, __VMLINUX_SYMBOL_STR(rdev_set_badblocks) },
	{ 0x376af15a, __VMLINUX_SYMBOL_STR(bio_reset) },
	{ 0x1cd0f6c0, __VMLINUX_SYMBOL_STR(mempool_alloc) },
	{ 0xdab06a1, __VMLINUX_SYMBOL_STR(bitmap_cond_end_sync) },
	{ 0x658f84a6, __VMLINUX_SYMBOL_STR(bitmap_start_sync) },
	{ 0x3b6b5624, __VMLINUX_SYMBOL_STR(bitmap_close_sync) },
	{ 0x5ebc344b, __VMLINUX_SYMBOL_STR(revalidate_disk) },
	{ 0x5bfb745c, __VMLINUX_SYMBOL_STR(md_set_array_sectors) },
	{ 0xa77e83e1, __VMLINUX_SYMBOL_STR(bitmap_resize) },
	{ 0xdbbae02b, __VMLINUX_SYMBOL_STR(md_allow_write) },
	{ 0xb2e39368, __VMLINUX_SYMBOL_STR(sysfs_create_link) },
	{ 0x974093a, __VMLINUX_SYMBOL_STR(sysfs_remove_link) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0x97a5e667, __VMLINUX_SYMBOL_STR(md_write_end) },
	{ 0x3f1a4a5e, __VMLINUX_SYMBOL_STR(bitmap_endwrite) },
	{ 0x6ae0f10b, __VMLINUX_SYMBOL_STR(contig_page_data) },
	{ 0x4d265394, __VMLINUX_SYMBOL_STR(put_page) },
	{ 0x815131ba, __VMLINUX_SYMBOL_STR(mempool_destroy) },
	{ 0xe36f653c, __VMLINUX_SYMBOL_STR(md_register_thread) },
	{ 0x63b87fc5, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x2b90cdaa, __VMLINUX_SYMBOL_STR(mempool_create) },
	{ 0x492621b9, __VMLINUX_SYMBOL_STR(__alloc_pages_nodemask) },
	{ 0xcaa1a2be, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x7b8c3a36, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x8893fa5d, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x158f2f00, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0x2fd85baf, __VMLINUX_SYMBOL_STR(___ratelimit) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x9c09faeb, __VMLINUX_SYMBOL_STR(bdevname) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x886d768, __VMLINUX_SYMBOL_STR(md_is_badblock) },
	{ 0x8c4e9857, __VMLINUX_SYMBOL_STR(md_cluster_ops) },
	{ 0x8f678b07, __VMLINUX_SYMBOL_STR(__stack_chk_guard) },
	{ 0x2d4e4ffd, __VMLINUX_SYMBOL_STR(md_wakeup_thread) },
	{ 0x343a1a8, __VMLINUX_SYMBOL_STR(__list_add) },
	{ 0xd0aa8d91, __VMLINUX_SYMBOL_STR(generic_make_request) },
	{ 0x4614dfd2, __VMLINUX_SYMBOL_STR(bitmap_unplug) },
	{ 0x44b1d426, __VMLINUX_SYMBOL_STR(__dynamic_pr_debug) },
	{ 0x920664c8, __VMLINUX_SYMBOL_STR(mempool_free) },
	{ 0xbd73db98, __VMLINUX_SYMBOL_STR(bio_put) },
	{ 0xad14fc55, __VMLINUX_SYMBOL_STR(bio_endio) },
	{ 0x43b0c9c3, __VMLINUX_SYMBOL_STR(preempt_schedule) },
	{ 0xb9e52429, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x706c5a65, __VMLINUX_SYMBOL_STR(preempt_count_sub) },
	{ 0xf229424a, __VMLINUX_SYMBOL_STR(preempt_count_add) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x2469810f, __VMLINUX_SYMBOL_STR(__rcu_read_unlock) },
	{ 0x8d522714, __VMLINUX_SYMBOL_STR(__rcu_read_lock) },
	{ 0xefd6cf06, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr0) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=md-mod";

