#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x9cef51a8, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xefe21d65, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0x40d2cb0b, __VMLINUX_SYMBOL_STR(unregister_md_personality) },
	{ 0x8d6117a4, __VMLINUX_SYMBOL_STR(register_md_personality) },
	{ 0x46d435a8, __VMLINUX_SYMBOL_STR(md_integrity_add_rdev) },
	{ 0x6091797f, __VMLINUX_SYMBOL_STR(synchronize_rcu) },
	{ 0x83d0c1e3, __VMLINUX_SYMBOL_STR(kernfs_notify) },
	{ 0x65e75cb6, __VMLINUX_SYMBOL_STR(__list_del_entry) },
	{ 0x48d12ad7, __VMLINUX_SYMBOL_STR(bio_copy_data) },
	{ 0x71c90087, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x292db41e, __VMLINUX_SYMBOL_STR(page_address) },
	{ 0xbd9074b1, __VMLINUX_SYMBOL_STR(blk_finish_plug) },
	{ 0x28d70d1c, __VMLINUX_SYMBOL_STR(submit_bio_wait) },
	{ 0x9b70e9c8, __VMLINUX_SYMBOL_STR(bio_alloc_mddev) },
	{ 0x8d3a6c2e, __VMLINUX_SYMBOL_STR(rdev_clear_badblocks) },
	{ 0x521445b, __VMLINUX_SYMBOL_STR(list_del) },
	{ 0x7d705738, __VMLINUX_SYMBOL_STR(blk_start_plug) },
	{ 0x4e2d22d, __VMLINUX_SYMBOL_STR(md_check_recovery) },
	{ 0x2196324, __VMLINUX_SYMBOL_STR(__aeabi_idiv) },
	{ 0x49ebacbd, __VMLINUX_SYMBOL_STR(_clear_bit) },
	{ 0xadc4d3c5, __VMLINUX_SYMBOL_STR(md_error) },
	{ 0x97fa1f35, __VMLINUX_SYMBOL_STR(sync_page_io) },
	{ 0xbcff3d85, __VMLINUX_SYMBOL_STR(kunmap) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x2d41e8fa, __VMLINUX_SYMBOL_STR(kmap) },
	{ 0xdf526040, __VMLINUX_SYMBOL_STR(md_wait_for_blocked_rdev) },
	{ 0xd27b25dd, __VMLINUX_SYMBOL_STR(blk_check_plugged) },
	{ 0x9d244f7b, __VMLINUX_SYMBOL_STR(bitmap_startwrite) },
	{ 0x3da35fa7, __VMLINUX_SYMBOL_STR(bio_trim) },
	{ 0x3fc58e56, __VMLINUX_SYMBOL_STR(bio_clone_mddev) },
	{ 0x499cb58c, __VMLINUX_SYMBOL_STR(prepare_to_wait) },
	{ 0x1592c45a, __VMLINUX_SYMBOL_STR(flush_signals) },
	{ 0xc8b57c27, __VMLINUX_SYMBOL_STR(autoremove_wake_function) },
	{ 0x329ae578, __VMLINUX_SYMBOL_STR(md_write_start) },
	{ 0x71d770ac, __VMLINUX_SYMBOL_STR(md_done_sync) },
	{ 0x3dacbb94, __VMLINUX_SYMBOL_STR(md_unregister_thread) },
	{ 0x4f428ff, __VMLINUX_SYMBOL_STR(md_integrity_register) },
	{ 0xcaf93c26, __VMLINUX_SYMBOL_STR(disk_stack_limits) },
	{ 0xdabe4370, __VMLINUX_SYMBOL_STR(blk_queue_max_write_same_sectors) },
	{ 0x40a9317a, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x2a3aa678, __VMLINUX_SYMBOL_STR(_test_and_clear_bit) },
	{ 0xf9c6390d, __VMLINUX_SYMBOL_STR(bio_free_pages) },
	{ 0x7b36a83, __VMLINUX_SYMBOL_STR(bio_alloc_pages) },
	{ 0xd599350a, __VMLINUX_SYMBOL_STR(bio_alloc_bioset) },
	{ 0x675076e1, __VMLINUX_SYMBOL_STR(bio_add_page) },
	{ 0xd0ee38b8, __VMLINUX_SYMBOL_STR(schedule_timeout_uninterruptible) },
	{ 0x9d427b0, __VMLINUX_SYMBOL_STR(bitmap_end_sync) },
	{ 0x6f1945fe, __VMLINUX_SYMBOL_STR(rdev_set_badblocks) },
	{ 0x1f581fb2, __VMLINUX_SYMBOL_STR(bio_reset) },
	{ 0x3026722, __VMLINUX_SYMBOL_STR(mempool_alloc) },
	{ 0x37939155, __VMLINUX_SYMBOL_STR(bitmap_cond_end_sync) },
	{ 0x625d4c6f, __VMLINUX_SYMBOL_STR(bitmap_start_sync) },
	{ 0x12082acc, __VMLINUX_SYMBOL_STR(bitmap_close_sync) },
	{ 0xcb4020cf, __VMLINUX_SYMBOL_STR(revalidate_disk) },
	{ 0x457f8ecd, __VMLINUX_SYMBOL_STR(md_set_array_sectors) },
	{ 0x10519bf, __VMLINUX_SYMBOL_STR(bitmap_resize) },
	{ 0x2ebd91db, __VMLINUX_SYMBOL_STR(md_allow_write) },
	{ 0x94022be8, __VMLINUX_SYMBOL_STR(sysfs_create_link) },
	{ 0x54c4b50f, __VMLINUX_SYMBOL_STR(sysfs_remove_link) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0xaeb9efe6, __VMLINUX_SYMBOL_STR(md_write_end) },
	{ 0xbbcb59c, __VMLINUX_SYMBOL_STR(bitmap_endwrite) },
	{ 0xf69ee7fe, __VMLINUX_SYMBOL_STR(contig_page_data) },
	{ 0x2ef3e65f, __VMLINUX_SYMBOL_STR(__put_page) },
	{ 0xa58fea9d, __VMLINUX_SYMBOL_STR(mempool_destroy) },
	{ 0x7836021c, __VMLINUX_SYMBOL_STR(md_register_thread) },
	{ 0x275ef902, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x2b4e956e, __VMLINUX_SYMBOL_STR(mempool_create) },
	{ 0xddfee4dd, __VMLINUX_SYMBOL_STR(__alloc_pages_nodemask) },
	{ 0x147fb690, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xf6789fdc, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x1cfb04fa, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x344b7739, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0x622598b1, __VMLINUX_SYMBOL_STR(init_wait_entry) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xd1ba148b, __VMLINUX_SYMBOL_STR(bdevname) },
	{ 0xba8bb333, __VMLINUX_SYMBOL_STR(___ratelimit) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x4a9ab10f, __VMLINUX_SYMBOL_STR(badblocks_check) },
	{ 0x72220dda, __VMLINUX_SYMBOL_STR(md_cluster_ops) },
	{ 0x8f678b07, __VMLINUX_SYMBOL_STR(__stack_chk_guard) },
	{ 0x343a1a8, __VMLINUX_SYMBOL_STR(__list_add) },
	{ 0x6afc3579, __VMLINUX_SYMBOL_STR(md_wakeup_thread) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0x3c161b96, __VMLINUX_SYMBOL_STR(generic_make_request) },
	{ 0x93584d3f, __VMLINUX_SYMBOL_STR(bitmap_unplug) },
	{ 0x69c03fc5, __VMLINUX_SYMBOL_STR(__dynamic_pr_debug) },
	{ 0x2232a8a5, __VMLINUX_SYMBOL_STR(mempool_free) },
	{ 0xc4105487, __VMLINUX_SYMBOL_STR(bio_put) },
	{ 0xca54fee, __VMLINUX_SYMBOL_STR(_test_and_set_bit) },
	{ 0xafa0c984, __VMLINUX_SYMBOL_STR(bio_endio) },
	{ 0x1a1431fd, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irq) },
	{ 0x3507a132, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irq) },
	{ 0xd85cd67e, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x51d559d1, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0x598542b2, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x2469810f, __VMLINUX_SYMBOL_STR(__rcu_read_unlock) },
	{ 0x8d522714, __VMLINUX_SYMBOL_STR(__rcu_read_lock) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=md-mod";

