#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x9cef51a8, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x5788a263, __VMLINUX_SYMBOL_STR(param_ops_bool) },
	{ 0x3655bcb1, __VMLINUX_SYMBOL_STR(bus_unregister) },
	{ 0x8375d79d, __VMLINUX_SYMBOL_STR(ida_destroy) },
	{ 0x4d72b5a7, __VMLINUX_SYMBOL_STR(device_unregister) },
	{ 0xcd6f8d90, __VMLINUX_SYMBOL_STR(bus_register) },
	{ 0x87715811, __VMLINUX_SYMBOL_STR(device_register) },
	{ 0xedf65a89, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0x466b85b8, __VMLINUX_SYMBOL_STR(libceph_compatible) },
	{ 0x1cfb04fa, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0x2c988955, __VMLINUX_SYMBOL_STR(prepare_to_wait_exclusive) },
	{ 0xc8b57c27, __VMLINUX_SYMBOL_STR(autoremove_wake_function) },
	{ 0x6b2e3bcd, __VMLINUX_SYMBOL_STR(ceph_get_snap_context) },
	{ 0xc1d9d2e4, __VMLINUX_SYMBOL_STR(blk_mq_start_request) },
	{ 0xf3a4eb81, __VMLINUX_SYMBOL_STR(blk_mq_end_request) },
	{ 0xea0b1ece, __VMLINUX_SYMBOL_STR(osd_req_op_raw_data_in_pages) },
	{ 0x7072a7c1, __VMLINUX_SYMBOL_STR(bio_advance) },
	{ 0x352d42e5, __VMLINUX_SYMBOL_STR(bio_clone_bioset) },
	{ 0x1f133aaa, __VMLINUX_SYMBOL_STR(fs_bio_set) },
	{ 0x767a75ff, __VMLINUX_SYMBOL_STR(device_add_disk) },
	{ 0xc6b76847, __VMLINUX_SYMBOL_STR(device_add) },
	{ 0x986abfdc, __VMLINUX_SYMBOL_STR(dev_set_name) },
	{ 0x71a50dbc, __VMLINUX_SYMBOL_STR(register_blkdev) },
	{ 0x343a1a8, __VMLINUX_SYMBOL_STR(__list_add) },
	{ 0x460562a6, __VMLINUX_SYMBOL_STR(ceph_open_session) },
	{ 0x550acacf, __VMLINUX_SYMBOL_STR(ceph_create_client) },
	{ 0x1eb926c4, __VMLINUX_SYMBOL_STR(blk_queue_max_discard_sectors) },
	{ 0x8d82c2fb, __VMLINUX_SYMBOL_STR(blk_queue_io_opt) },
	{ 0x73e26f50, __VMLINUX_SYMBOL_STR(blk_queue_io_min) },
	{ 0x29ba16dc, __VMLINUX_SYMBOL_STR(blk_queue_max_segment_size) },
	{ 0x8aec2e1, __VMLINUX_SYMBOL_STR(blk_queue_max_segments) },
	{ 0xd086d411, __VMLINUX_SYMBOL_STR(blk_queue_max_hw_sectors) },
	{ 0x60cdc00a, __VMLINUX_SYMBOL_STR(blk_mq_init_queue) },
	{ 0x3dcc8f63, __VMLINUX_SYMBOL_STR(blk_mq_alloc_tag_set) },
	{ 0xb81960ca, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0x4b2dcc2b, __VMLINUX_SYMBOL_STR(alloc_disk) },
	{ 0x326439b1, __VMLINUX_SYMBOL_STR(__module_get) },
	{ 0x43a53735, __VMLINUX_SYMBOL_STR(__alloc_workqueue_key) },
	{ 0xcbee6439, __VMLINUX_SYMBOL_STR(ida_simple_get) },
	{ 0x609b230a, __VMLINUX_SYMBOL_STR(ceph_monc_wait_osdmap) },
	{ 0x3559ade9, __VMLINUX_SYMBOL_STR(ceph_osdc_maybe_request_map) },
	{ 0x1c084f27, __VMLINUX_SYMBOL_STR(ceph_monc_get_version) },
	{ 0x67f59808, __VMLINUX_SYMBOL_STR(ceph_pg_poolid_by_name) },
	{ 0x1f77a75b, __VMLINUX_SYMBOL_STR(ceph_destroy_options) },
	{ 0x6be38ba4, __VMLINUX_SYMBOL_STR(ceph_compare_options) },
	{ 0x3e5d16fb, __VMLINUX_SYMBOL_STR(ceph_parse_options) },
	{ 0xe2fae716, __VMLINUX_SYMBOL_STR(kmemdup) },
	{ 0x6c1ce5ce, __VMLINUX_SYMBOL_STR(strcspn) },
	{ 0xc7ec6c27, __VMLINUX_SYMBOL_STR(strspn) },
	{ 0xb8e4fba7, __VMLINUX_SYMBOL_STR(try_module_get) },
	{ 0xf1af15a7, __VMLINUX_SYMBOL_STR(ceph_pg_pool_name_by_id) },
	{ 0xcb4020cf, __VMLINUX_SYMBOL_STR(revalidate_disk) },
	{ 0xd9ce8f0c, __VMLINUX_SYMBOL_STR(strnlen) },
	{ 0xae3515ba, __VMLINUX_SYMBOL_STR(ceph_create_snap_context) },
	{ 0xc499ae1e, __VMLINUX_SYMBOL_STR(kstrdup) },
	{ 0x7da021ce, __VMLINUX_SYMBOL_STR(ceph_copy_from_page_vector) },
	{ 0x5fcfbc46, __VMLINUX_SYMBOL_STR(osd_req_op_cls_response_data_pages) },
	{ 0x48f7d1f6, __VMLINUX_SYMBOL_STR(osd_req_op_cls_request_data_pagelist) },
	{ 0xd813625e, __VMLINUX_SYMBOL_STR(ceph_pagelist_append) },
	{ 0xf0079d2c, __VMLINUX_SYMBOL_STR(ceph_alloc_page_vector) },
	{ 0x6079cbf7, __VMLINUX_SYMBOL_STR(ceph_osdc_cancel_request) },
	{ 0x6c6cdd4d, __VMLINUX_SYMBOL_STR(wait_for_completion_interruptible_timeout) },
	{ 0xc0ac049d, __VMLINUX_SYMBOL_STR(blk_set_queue_dying) },
	{ 0x459302e2, __VMLINUX_SYMBOL_STR(blk_mq_freeze_queue) },
	{ 0xb5a459dc, __VMLINUX_SYMBOL_STR(unregister_blkdev) },
	{ 0xad9516b4, __VMLINUX_SYMBOL_STR(device_del) },
	{ 0x65e75cb6, __VMLINUX_SYMBOL_STR(__list_del_entry) },
	{ 0x7c9ffabf, __VMLINUX_SYMBOL_STR(ceph_osdc_watch) },
	{ 0x8c675af8, __VMLINUX_SYMBOL_STR(mod_delayed_work_on) },
	{ 0x292db41e, __VMLINUX_SYMBOL_STR(page_address) },
	{ 0xd85cd67e, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x45d63fe1, __VMLINUX_SYMBOL_STR(cancel_delayed_work) },
	{ 0xfa170121, __VMLINUX_SYMBOL_STR(ceph_osdc_sync) },
	{ 0xd9d2eaeb, __VMLINUX_SYMBOL_STR(downgrade_write) },
	{ 0xa7e52e57, __VMLINUX_SYMBOL_STR(osd_req_op_cls_request_data_pages) },
	{ 0x66f082cf, __VMLINUX_SYMBOL_STR(osd_req_op_cls_init) },
	{ 0x620f3c34, __VMLINUX_SYMBOL_STR(__blk_mq_end_request) },
	{ 0x642d5ec1, __VMLINUX_SYMBOL_STR(blk_update_request) },
	{ 0x49ebacbd, __VMLINUX_SYMBOL_STR(_clear_bit) },
	{ 0xf8dfe3ad, __VMLINUX_SYMBOL_STR(put_device) },
	{ 0x3f688151, __VMLINUX_SYMBOL_STR(ceph_put_snap_context) },
	{ 0x85d472aa, __VMLINUX_SYMBOL_STR(queue_delayed_work_on) },
	{ 0x229b20b2, __VMLINUX_SYMBOL_STR(up_write) },
	{ 0x7cbdf731, __VMLINUX_SYMBOL_STR(down_write) },
	{ 0xa382e798, __VMLINUX_SYMBOL_STR(ceph_osdc_flush_notifies) },
	{ 0x4205ad24, __VMLINUX_SYMBOL_STR(cancel_work_sync) },
	{ 0xa0744ea9, __VMLINUX_SYMBOL_STR(cancel_delayed_work_sync) },
	{ 0x57366f57, __VMLINUX_SYMBOL_STR(ceph_osdc_unwatch) },
	{ 0xbe81b2ae, __VMLINUX_SYMBOL_STR(ceph_osdc_start_request) },
	{ 0x4554c349, __VMLINUX_SYMBOL_STR(ceph_cls_unlock) },
	{ 0xca54fee, __VMLINUX_SYMBOL_STR(_test_and_set_bit) },
	{ 0x657b2089, __VMLINUX_SYMBOL_STR(get_device) },
	{ 0x23b0db80, __VMLINUX_SYMBOL_STR(set_disk_ro) },
	{ 0x1a1431fd, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irq) },
	{ 0x3507a132, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irq) },
	{ 0x353e3fa5, __VMLINUX_SYMBOL_STR(__get_user_4) },
	{ 0x14846fbb, __VMLINUX_SYMBOL_STR(module_put) },
	{ 0x29e1b020, __VMLINUX_SYMBOL_STR(ida_simple_remove) },
	{ 0x8c03d20c, __VMLINUX_SYMBOL_STR(destroy_workqueue) },
	{ 0x9d46f43d, __VMLINUX_SYMBOL_STR(ceph_oloc_destroy) },
	{ 0x2101cbc9, __VMLINUX_SYMBOL_STR(ceph_oid_destroy) },
	{ 0xb579c05b, __VMLINUX_SYMBOL_STR(ceph_osdc_notify_ack) },
	{ 0xeec95d62, __VMLINUX_SYMBOL_STR(ceph_osdc_notify) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x84b183ae, __VMLINUX_SYMBOL_STR(strncmp) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0x32970def, __VMLINUX_SYMBOL_STR(ceph_cls_break_lock) },
	{ 0x92ce20e7, __VMLINUX_SYMBOL_STR(ceph_monc_blacklist_add) },
	{ 0xdfc091f9, __VMLINUX_SYMBOL_STR(ceph_entity_type_name) },
	{ 0x71c90087, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x20c55ae0, __VMLINUX_SYMBOL_STR(sscanf) },
	{ 0xbf28ebfa, __VMLINUX_SYMBOL_STR(ceph_free_lockers) },
	{ 0x20bab79e, __VMLINUX_SYMBOL_STR(ceph_osdc_list_watchers) },
	{ 0xf20d758f, __VMLINUX_SYMBOL_STR(ceph_cls_lock_info) },
	{ 0x60e8969d, __VMLINUX_SYMBOL_STR(ceph_cls_lock) },
	{ 0x9a1781b9, __VMLINUX_SYMBOL_STR(ceph_client_addr) },
	{ 0x981561a4, __VMLINUX_SYMBOL_STR(ceph_client_gid) },
	{ 0xab694444, __VMLINUX_SYMBOL_STR(bsearch) },
	{ 0x81f3afb, __VMLINUX_SYMBOL_STR(complete_all) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0x49163ab3, __VMLINUX_SYMBOL_STR(kmap_atomic) },
	{ 0xed93f29e, __VMLINUX_SYMBOL_STR(__kunmap_atomic) },
	{ 0xe9785bb8, __VMLINUX_SYMBOL_STR(flush_dcache_page) },
	{ 0xad17d58a, __VMLINUX_SYMBOL_STR(ceph_destroy_client) },
	{ 0x5fc56a46, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0x521445b, __VMLINUX_SYMBOL_STR(list_del) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0xb7ea6eb1, __VMLINUX_SYMBOL_STR(osd_req_op_extent_osd_data_pages) },
	{ 0xefaa92db, __VMLINUX_SYMBOL_STR(osd_req_op_extent_osd_data_bio) },
	{ 0x92427d36, __VMLINUX_SYMBOL_STR(osd_req_op_init) },
	{ 0x7a2add7d, __VMLINUX_SYMBOL_STR(current_kernel_time64) },
	{ 0xef9dffa5, __VMLINUX_SYMBOL_STR(osd_req_op_alloc_hint_init) },
	{ 0x52032cea, __VMLINUX_SYMBOL_STR(osd_req_op_extent_init) },
	{ 0xbe7630e9, __VMLINUX_SYMBOL_STR(ceph_release_page_vector) },
	{ 0xc4105487, __VMLINUX_SYMBOL_STR(bio_put) },
	{ 0xd26e0e90, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0x55913380, __VMLINUX_SYMBOL_STR(up_read) },
	{ 0xadbfbef8, __VMLINUX_SYMBOL_STR(down_read) },
	{ 0x262b5646, __VMLINUX_SYMBOL_STR(ceph_osdc_put_request) },
	{ 0x6544a707, __VMLINUX_SYMBOL_STR(ceph_osdc_alloc_messages) },
	{ 0xbf15e03c, __VMLINUX_SYMBOL_STR(ceph_oid_aprintf) },
	{ 0xb62ec2d, __VMLINUX_SYMBOL_STR(ceph_osdc_alloc_request) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x666774aa, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x97255bdf, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x76e9f2ae, __VMLINUX_SYMBOL_STR(device_initialize) },
	{ 0x275ef902, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x8fdf772a, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x5a32f871, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0x2a07e2a8, __VMLINUX_SYMBOL_STR(__init_rwsem) },
	{ 0x147fb690, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xf6789fdc, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x4e3567f7, __VMLINUX_SYMBOL_STR(match_int) },
	{ 0x44e9a829, __VMLINUX_SYMBOL_STR(match_token) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x6e4d862d, __VMLINUX_SYMBOL_STR(blk_mq_free_tag_set) },
	{ 0xf6140fe2, __VMLINUX_SYMBOL_STR(blk_cleanup_queue) },
	{ 0x115c2e99, __VMLINUX_SYMBOL_STR(del_gendisk) },
	{ 0xbf4c34d6, __VMLINUX_SYMBOL_STR(put_disk) },
	{ 0xb2d48a2e, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0x69c03fc5, __VMLINUX_SYMBOL_STR(__dynamic_pr_debug) },
	{ 0xdbe8baac, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0xfed0a669, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0x10ab577b, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x8f678b07, __VMLINUX_SYMBOL_STR(__stack_chk_guard) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=libceph";

