#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x2c197ea3, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xa57b02d8, __VMLINUX_SYMBOL_STR(param_ops_bool) },
	{ 0x97c99553, __VMLINUX_SYMBOL_STR(blk_mq_map_queue) },
	{ 0xaeed7e14, __VMLINUX_SYMBOL_STR(bus_unregister) },
	{ 0xe6252d2c, __VMLINUX_SYMBOL_STR(ida_destroy) },
	{ 0x8c03d20c, __VMLINUX_SYMBOL_STR(destroy_workqueue) },
	{ 0x684ff483, __VMLINUX_SYMBOL_STR(device_unregister) },
	{ 0x9ef08901, __VMLINUX_SYMBOL_STR(bus_register) },
	{ 0xb2797252, __VMLINUX_SYMBOL_STR(device_register) },
	{ 0x43a53735, __VMLINUX_SYMBOL_STR(__alloc_workqueue_key) },
	{ 0x71aa3ade, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0x466b85b8, __VMLINUX_SYMBOL_STR(libceph_compatible) },
	{ 0x6b2e3bcd, __VMLINUX_SYMBOL_STR(ceph_get_snap_context) },
	{ 0x67f1d6ab, __VMLINUX_SYMBOL_STR(blk_mq_start_request) },
	{ 0xd0b692d2, __VMLINUX_SYMBOL_STR(blk_mq_end_request) },
	{ 0xfa75d80d, __VMLINUX_SYMBOL_STR(osd_req_op_raw_data_in_pages) },
	{ 0xdb553086, __VMLINUX_SYMBOL_STR(bio_advance) },
	{ 0x3e7d8653, __VMLINUX_SYMBOL_STR(bio_clone_bioset) },
	{ 0x8ab843c5, __VMLINUX_SYMBOL_STR(fs_bio_set) },
	{ 0x6a3868ff, __VMLINUX_SYMBOL_STR(add_disk) },
	{ 0x71a50dbc, __VMLINUX_SYMBOL_STR(register_blkdev) },
	{ 0xf080ed1a, __VMLINUX_SYMBOL_STR(device_add) },
	{ 0xd035cb86, __VMLINUX_SYMBOL_STR(dev_set_name) },
	{ 0xcf08c24, __VMLINUX_SYMBOL_STR(blk_queue_max_discard_sectors) },
	{ 0x447d9618, __VMLINUX_SYMBOL_STR(blk_queue_io_opt) },
	{ 0x8d08ac64, __VMLINUX_SYMBOL_STR(blk_queue_io_min) },
	{ 0xa3975616, __VMLINUX_SYMBOL_STR(blk_queue_max_segment_size) },
	{ 0x4812a5fe, __VMLINUX_SYMBOL_STR(blk_queue_max_segments) },
	{ 0x288bd629, __VMLINUX_SYMBOL_STR(blk_queue_max_hw_sectors) },
	{ 0x31bf9fbc, __VMLINUX_SYMBOL_STR(blk_mq_init_queue) },
	{ 0xfbe39272, __VMLINUX_SYMBOL_STR(blk_mq_alloc_tag_set) },
	{ 0xb81960ca, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0x550fdba2, __VMLINUX_SYMBOL_STR(alloc_disk) },
	{ 0xcc7508db, __VMLINUX_SYMBOL_STR(ida_simple_get) },
	{ 0x343a1a8, __VMLINUX_SYMBOL_STR(__list_add) },
	{ 0x2f2bb1cc, __VMLINUX_SYMBOL_STR(ceph_open_session) },
	{ 0xe5011dbd, __VMLINUX_SYMBOL_STR(ceph_create_client) },
	{ 0xbcc4d1eb, __VMLINUX_SYMBOL_STR(ceph_monc_wait_osdmap) },
	{ 0x1f0f60fd, __VMLINUX_SYMBOL_STR(ceph_monc_request_next_osdmap) },
	{ 0xbebd8eed, __VMLINUX_SYMBOL_STR(ceph_monc_do_get_version) },
	{ 0x6c8d360e, __VMLINUX_SYMBOL_STR(ceph_pg_poolid_by_name) },
	{ 0x62b72b0d, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0xc7672334, __VMLINUX_SYMBOL_STR(ceph_destroy_options) },
	{ 0x30eb7384, __VMLINUX_SYMBOL_STR(ceph_compare_options) },
	{ 0xe16b893b, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x40e9fb59, __VMLINUX_SYMBOL_STR(ceph_parse_options) },
	{ 0xe2fae716, __VMLINUX_SYMBOL_STR(kmemdup) },
	{ 0x6c1ce5ce, __VMLINUX_SYMBOL_STR(strcspn) },
	{ 0xc7ec6c27, __VMLINUX_SYMBOL_STR(strspn) },
	{ 0x9e931cfd, __VMLINUX_SYMBOL_STR(try_module_get) },
	{ 0xab57f30c, __VMLINUX_SYMBOL_STR(ceph_pg_pool_name_by_id) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0xf280a782, __VMLINUX_SYMBOL_STR(ceph_osdc_create_event) },
	{ 0x5ebc344b, __VMLINUX_SYMBOL_STR(revalidate_disk) },
	{ 0x6f3db115, __VMLINUX_SYMBOL_STR(up_write) },
	{ 0xbc5c84b5, __VMLINUX_SYMBOL_STR(down_write) },
	{ 0xd9ce8f0c, __VMLINUX_SYMBOL_STR(strnlen) },
	{ 0x71c90087, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0xae3515ba, __VMLINUX_SYMBOL_STR(ceph_create_snap_context) },
	{ 0xc499ae1e, __VMLINUX_SYMBOL_STR(kstrdup) },
	{ 0xcaea4ce, __VMLINUX_SYMBOL_STR(ceph_copy_from_page_vector) },
	{ 0x7103ad92, __VMLINUX_SYMBOL_STR(osd_req_op_cls_response_data_pages) },
	{ 0xc4d72633, __VMLINUX_SYMBOL_STR(osd_req_op_cls_request_data_pagelist) },
	{ 0xd813625e, __VMLINUX_SYMBOL_STR(ceph_pagelist_append) },
	{ 0x29460385, __VMLINUX_SYMBOL_STR(ceph_alloc_page_vector) },
	{ 0xb5a459dc, __VMLINUX_SYMBOL_STR(unregister_blkdev) },
	{ 0xe8f0c061, __VMLINUX_SYMBOL_STR(device_del) },
	{ 0xccefeb0e, __VMLINUX_SYMBOL_STR(ceph_osdc_flush_notifies) },
	{ 0x996bdb64, __VMLINUX_SYMBOL_STR(_kstrtoul) },
	{ 0x7c8e67a0, __VMLINUX_SYMBOL_STR(put_device) },
	{ 0x8b204bd2, __VMLINUX_SYMBOL_STR(osd_req_op_cls_request_data_pages) },
	{ 0xdec87d04, __VMLINUX_SYMBOL_STR(osd_req_op_cls_init) },
	{ 0x4418333d, __VMLINUX_SYMBOL_STR(__blk_mq_end_request) },
	{ 0x5a73283a, __VMLINUX_SYMBOL_STR(blk_update_request) },
	{ 0x3f688151, __VMLINUX_SYMBOL_STR(ceph_put_snap_context) },
	{ 0xf2c482be, __VMLINUX_SYMBOL_STR(ida_simple_remove) },
	{ 0x65e75cb6, __VMLINUX_SYMBOL_STR(__list_del_entry) },
	{ 0xe818e26b, __VMLINUX_SYMBOL_STR(ceph_osdc_cancel_event) },
	{ 0xac332bb1, __VMLINUX_SYMBOL_STR(ceph_osdc_set_request_linger) },
	{ 0xb1b49f81, __VMLINUX_SYMBOL_STR(osd_req_op_watch_init) },
	{ 0x3836942c, __VMLINUX_SYMBOL_STR(osd_req_op_extent_osd_data_pages) },
	{ 0x23ba2cc4, __VMLINUX_SYMBOL_STR(osd_req_op_extent_osd_data_bio) },
	{ 0x5aec6233, __VMLINUX_SYMBOL_STR(osd_req_op_init) },
	{ 0x63e70a5d, __VMLINUX_SYMBOL_STR(osd_req_op_alloc_hint_init) },
	{ 0xec57f643, __VMLINUX_SYMBOL_STR(osd_req_op_extent_init) },
	{ 0x7a2add7d, __VMLINUX_SYMBOL_STR(current_kernel_time64) },
	{ 0xead9b982, __VMLINUX_SYMBOL_STR(ceph_osdc_build_request) },
	{ 0xbd73db98, __VMLINUX_SYMBOL_STR(bio_put) },
	{ 0xf4b6cdae, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0xa4ece84a, __VMLINUX_SYMBOL_STR(ceph_release_page_vector) },
	{ 0x38b0e868, __VMLINUX_SYMBOL_STR(ceph_osdc_put_request) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xd9ff3ac3, __VMLINUX_SYMBOL_STR(get_device) },
	{ 0xb2d48a2e, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0xb68c967f, __VMLINUX_SYMBOL_STR(set_disk_ro) },
	{ 0x353e3fa5, __VMLINUX_SYMBOL_STR(__get_user_4) },
	{ 0x8abe423d, __VMLINUX_SYMBOL_STR(ceph_client_id) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0xab694444, __VMLINUX_SYMBOL_STR(bsearch) },
	{ 0xd74f9f2e, __VMLINUX_SYMBOL_STR(__module_get) },
	{ 0xff58b518, __VMLINUX_SYMBOL_STR(device_initialize) },
	{ 0x719e5acf, __VMLINUX_SYMBOL_STR(__init_rwsem) },
	{ 0x2d9b9ea6, __VMLINUX_SYMBOL_STR(module_put) },
	{ 0x43b0c9c3, __VMLINUX_SYMBOL_STR(preempt_schedule) },
	{ 0xd9f0bb7c, __VMLINUX_SYMBOL_STR(ceph_destroy_client) },
	{ 0x706c5a65, __VMLINUX_SYMBOL_STR(preempt_count_sub) },
	{ 0x521445b, __VMLINUX_SYMBOL_STR(list_del) },
	{ 0xf229424a, __VMLINUX_SYMBOL_STR(preempt_count_add) },
	{ 0x4e3567f7, __VMLINUX_SYMBOL_STR(match_int) },
	{ 0x44e9a829, __VMLINUX_SYMBOL_STR(match_token) },
	{ 0xd4628b98, __VMLINUX_SYMBOL_STR(blk_mq_free_tag_set) },
	{ 0x8dc00423, __VMLINUX_SYMBOL_STR(blk_cleanup_queue) },
	{ 0x251b483d, __VMLINUX_SYMBOL_STR(del_gendisk) },
	{ 0xdb6afd09, __VMLINUX_SYMBOL_STR(put_disk) },
	{ 0x87a10d5, __VMLINUX_SYMBOL_STR(wait_for_completion_interruptible_timeout) },
	{ 0xa958115, __VMLINUX_SYMBOL_STR(ceph_osdc_start_request) },
	{ 0xdf98c806, __VMLINUX_SYMBOL_STR(complete_all) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0x195f8049, __VMLINUX_SYMBOL_STR(ceph_osdc_alloc_request) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0xd1a5deac, __VMLINUX_SYMBOL_STR(kmap_atomic) },
	{ 0xed93f29e, __VMLINUX_SYMBOL_STR(__kunmap_atomic) },
	{ 0xb9a1aebe, __VMLINUX_SYMBOL_STR(flush_dcache_page) },
	{ 0x26c06d6c, __VMLINUX_SYMBOL_STR(up_read) },
	{ 0x9101360b, __VMLINUX_SYMBOL_STR(down_read) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xf9dd9922, __VMLINUX_SYMBOL_STR(__init_swait_queue_head) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x55184b5d, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x97255bdf, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0xcaa1a2be, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x7b8c3a36, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x44b1d426, __VMLINUX_SYMBOL_STR(__dynamic_pr_debug) },
	{ 0xe93df040, __VMLINUX_SYMBOL_STR(ceph_osdc_cancel_request) },
	{ 0xb5233f3e, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x8f678b07, __VMLINUX_SYMBOL_STR(__stack_chk_guard) },
	{ 0xefd6cf06, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr0) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=libceph";

