#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x2c197ea3, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x59814a84, __VMLINUX_SYMBOL_STR(dccp_statistics) },
	{ 0x4aa283e5, __VMLINUX_SYMBOL_STR(dccp_init_sock) },
	{ 0x4ce053bd, __VMLINUX_SYMBOL_STR(__kfree_skb) },
	{ 0xc690dfb0, __VMLINUX_SYMBOL_STR(dccp_v4_do_rcv) },
	{ 0xcec41117, __VMLINUX_SYMBOL_STR(inet6_csk_update_pmtu) },
	{ 0xb19b67bc, __VMLINUX_SYMBOL_STR(dccp_set_state) },
	{ 0x3bfac108, __VMLINUX_SYMBOL_STR(inet6_csk_bind_conflict) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0xaaacc8e4, __VMLINUX_SYMBOL_STR(ipv6_getsockopt) },
	{ 0xccf945e0, __VMLINUX_SYMBOL_STR(inet_unhash) },
	{ 0x2f5ad43d, __VMLINUX_SYMBOL_STR(inet_twsk_put) },
	{ 0xac87d37d, __VMLINUX_SYMBOL_STR(dccp_hashinfo) },
	{ 0xf3a2bad2, __VMLINUX_SYMBOL_STR(inet6_add_protocol) },
	{ 0x9f414cf0, __VMLINUX_SYMBOL_STR(inet6_lookup_listener) },
	{ 0x761b5ae1, __VMLINUX_SYMBOL_STR(dccp_sendmsg) },
	{ 0xf40aaf0e, __VMLINUX_SYMBOL_STR(ipv6_opt_accepted) },
	{ 0xe174fd04, __VMLINUX_SYMBOL_STR(sk_setup_caps) },
	{ 0xc6544dcc, __VMLINUX_SYMBOL_STR(dccp_ctl_make_reset) },
	{ 0x44e8c34e, __VMLINUX_SYMBOL_STR(dccp_destroy_sock) },
	{ 0xcfccc2bc, __VMLINUX_SYMBOL_STR(dccp_make_response) },
	{ 0x71997d11, __VMLINUX_SYMBOL_STR(sock_release) },
	{ 0x86253b33, __VMLINUX_SYMBOL_STR(dst_release) },
	{ 0xd1a46981, __VMLINUX_SYMBOL_STR(skb_clone) },
	{ 0xc0e27b6f, __VMLINUX_SYMBOL_STR(dccp_rcv_established) },
	{ 0x16c6997b, __VMLINUX_SYMBOL_STR(dccp_req_err) },
	{ 0xb0b4d158, __VMLINUX_SYMBOL_STR(security_skb_classify_flow) },
	{ 0xfc4ee84c, __VMLINUX_SYMBOL_STR(dccp_v4_conn_request) },
	{ 0x5f31621d, __VMLINUX_SYMBOL_STR(inet_csk_prepare_forced_close) },
	{ 0x7ed8e2a6, __VMLINUX_SYMBOL_STR(dccp_create_openreq_child) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0xbf1ed221, __VMLINUX_SYMBOL_STR(ipv6_dup_options) },
	{ 0x1be6f4ac, __VMLINUX_SYMBOL_STR(dccp_check_req) },
	{ 0xe60c41fc, __VMLINUX_SYMBOL_STR(inet_sendmsg) },
	{ 0xf6ac9aec, __VMLINUX_SYMBOL_STR(inet6_release) },
	{ 0xb0d888b, __VMLINUX_SYMBOL_STR(icmpv6_err_convert) },
	{ 0xb1151748, __VMLINUX_SYMBOL_STR(inet6_register_protosw) },
	{ 0x2e4920ed, __VMLINUX_SYMBOL_STR(dccp_recvmsg) },
	{ 0x1bcc0da7, __VMLINUX_SYMBOL_STR(ip6_xmit) },
	{ 0x5c0712, __VMLINUX_SYMBOL_STR(inet_sk_rebuild_header) },
	{ 0xc38259af, __VMLINUX_SYMBOL_STR(__this_cpu_preempt_check) },
	{ 0x983e3c3b, __VMLINUX_SYMBOL_STR(inet6_getname) },
	{ 0x406d9bd, __VMLINUX_SYMBOL_STR(sock_rfree) },
	{ 0xdd8ba19f, __VMLINUX_SYMBOL_STR(inet6_csk_xmit) },
	{ 0xdc96a550, __VMLINUX_SYMBOL_STR(dccp_ioctl) },
	{ 0x6e59997a, __VMLINUX_SYMBOL_STR(dccp_setsockopt) },
	{ 0xc4178b3e, __VMLINUX_SYMBOL_STR(sock_common_recvmsg) },
	{ 0xcd3deea0, __VMLINUX_SYMBOL_STR(sock_no_sendpage) },
	{ 0x6d2abf1a, __VMLINUX_SYMBOL_STR(dccp_child_process) },
	{ 0xf8c694e4, __VMLINUX_SYMBOL_STR(sock_no_mmap) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0xcf159dde, __VMLINUX_SYMBOL_STR(sock_no_socketpair) },
	{ 0x3ab00428, __VMLINUX_SYMBOL_STR(skb_checksum) },
	{ 0x88d07c3e, __VMLINUX_SYMBOL_STR(ip6_dst_lookup_flow) },
	{ 0x95f58b2d, __VMLINUX_SYMBOL_STR(unregister_pernet_subsys) },
	{ 0x706c5a65, __VMLINUX_SYMBOL_STR(preempt_count_sub) },
	{ 0x39f49742, __VMLINUX_SYMBOL_STR(__inet6_lookup_established) },
	{ 0x1ecd1d38, __VMLINUX_SYMBOL_STR(dccp_v4_request_recv_sock) },
	{ 0x81116ca2, __VMLINUX_SYMBOL_STR(dccp_parse_options) },
	{ 0xc095f13c, __VMLINUX_SYMBOL_STR(dccp_getsockopt) },
	{ 0xc2a7502f, __VMLINUX_SYMBOL_STR(security_sk_classify_flow) },
	{ 0x1dcb6871, __VMLINUX_SYMBOL_STR(inet6_ioctl) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x393e4a81, __VMLINUX_SYMBOL_STR(inet6_csk_route_req) },
	{ 0x8aa619e2, __VMLINUX_SYMBOL_STR(fl6_sock_lookup) },
	{ 0xffb74af4, __VMLINUX_SYMBOL_STR(fl6_update_dst) },
	{ 0xf4b6cdae, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x815dd47, __VMLINUX_SYMBOL_STR(dccp_reqsk_init) },
	{ 0x381113bb, __VMLINUX_SYMBOL_STR(dccp_close) },
	{ 0xbd392c2a, __VMLINUX_SYMBOL_STR(sk_free) },
	{ 0x51f9e87b, __VMLINUX_SYMBOL_STR(inet_shutdown) },
	{ 0x433441f4, __VMLINUX_SYMBOL_STR(dccp_orphan_count) },
	{ 0x2469810f, __VMLINUX_SYMBOL_STR(__rcu_read_unlock) },
	{ 0xd462609, __VMLINUX_SYMBOL_STR(dccp_sync_mss) },
	{ 0x43b0c9c3, __VMLINUX_SYMBOL_STR(preempt_schedule) },
	{ 0xb03c7c69, __VMLINUX_SYMBOL_STR(inet6_hash_connect) },
	{ 0x961143e5, __VMLINUX_SYMBOL_STR(inet_accept) },
	{ 0x805ab8e4, __VMLINUX_SYMBOL_STR(inet_csk_reqsk_queue_drop_and_put) },
	{ 0xad5e3b0, __VMLINUX_SYMBOL_STR(sk_filter_trim_cap) },
	{ 0x7ee078b, __VMLINUX_SYMBOL_STR(inet_csk_get_port) },
	{ 0xb2c1309c, __VMLINUX_SYMBOL_STR(dccp_death_row) },
	{ 0x64203dbd, __VMLINUX_SYMBOL_STR(inet_ctl_sock_create) },
	{ 0x3c3e091, __VMLINUX_SYMBOL_STR(dccp_poll) },
	{ 0xb89fcc4b, __VMLINUX_SYMBOL_STR(inet_hash) },
	{ 0xb931c958, __VMLINUX_SYMBOL_STR(proto_register) },
	{ 0x32f083ce, __VMLINUX_SYMBOL_STR(dccp_disconnect) },
	{ 0xcefc11c8, __VMLINUX_SYMBOL_STR(__sk_dst_check) },
	{ 0x9bf7b702, __VMLINUX_SYMBOL_STR(dccp_done) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0xd648b81f, __VMLINUX_SYMBOL_STR(inet_reqsk_alloc) },
	{ 0x28dfed6e, __VMLINUX_SYMBOL_STR(dccp_v4_send_check) },
	{ 0x4a211dfd, __VMLINUX_SYMBOL_STR(kfree_skb) },
	{ 0x448c5843, __VMLINUX_SYMBOL_STR(proto_unregister) },
	{ 0xe0a1fc88, __VMLINUX_SYMBOL_STR(inet_stream_connect) },
	{ 0x2207b3c5, __VMLINUX_SYMBOL_STR(dccp_invalid_packet) },
	{ 0x2ab0a235, __VMLINUX_SYMBOL_STR(inet6_del_protocol) },
	{ 0x9f856790, __VMLINUX_SYMBOL_STR(inet_ehash_nolisten) },
	{ 0xb99f0242, __VMLINUX_SYMBOL_STR(register_pernet_subsys) },
	{ 0x4cdd391d, __VMLINUX_SYMBOL_STR(dccp_feat_list_purge) },
	{ 0x784331c8, __VMLINUX_SYMBOL_STR(dccp_syn_ack_timeout) },
	{ 0xd9aa68c1, __VMLINUX_SYMBOL_STR(sk_receive_skb) },
	{ 0xcb26d87b, __VMLINUX_SYMBOL_STR(inet_csk_reqsk_queue_hash_add) },
	{ 0x738a4a34, __VMLINUX_SYMBOL_STR(ipv6_setsockopt) },
	{ 0xf6ebc03b, __VMLINUX_SYMBOL_STR(net_ratelimit) },
	{ 0xc54b8106, __VMLINUX_SYMBOL_STR(sock_common_setsockopt) },
	{ 0x25df4b8b, __VMLINUX_SYMBOL_STR(inet6_sk_rebuild_header) },
	{ 0xeacf846a, __VMLINUX_SYMBOL_STR(__xfrm_policy_check) },
	{ 0x44da5d0f, __VMLINUX_SYMBOL_STR(__csum_ipv6_magic) },
	{ 0x20ecd82f, __VMLINUX_SYMBOL_STR(security_req_classify_flow) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xe1761617, __VMLINUX_SYMBOL_STR(security_inet_conn_request) },
	{ 0x4758ee4f, __VMLINUX_SYMBOL_STR(inet_dccp_listen) },
	{ 0x260081f7, __VMLINUX_SYMBOL_STR(__inet_inherit_port) },
	{ 0x8e23da49, __VMLINUX_SYMBOL_STR(sock_common_getsockopt) },
	{ 0xe200f872, __VMLINUX_SYMBOL_STR(secure_dccpv6_sequence_number) },
	{ 0x1ce3b1d0, __VMLINUX_SYMBOL_STR(inet6_unregister_protosw) },
	{ 0xefd6cf06, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr0) },
	{ 0x3aa7ed21, __VMLINUX_SYMBOL_STR(inet_csk_accept) },
	{ 0x8f678b07, __VMLINUX_SYMBOL_STR(__stack_chk_guard) },
	{ 0x98a2538, __VMLINUX_SYMBOL_STR(inet6_bind) },
	{ 0xed38dcc0, __VMLINUX_SYMBOL_STR(dccp_reqsk_send_ack) },
	{ 0x508550f4, __VMLINUX_SYMBOL_STR(dccp_rcv_state_process) },
	{ 0x1d8f4c65, __VMLINUX_SYMBOL_STR(consume_skb) },
	{ 0x4eea068b, __VMLINUX_SYMBOL_STR(dccp_connect) },
	{ 0x2b1ff1d0, __VMLINUX_SYMBOL_STR(dccp_shutdown) },
	{ 0x8d522714, __VMLINUX_SYMBOL_STR(__rcu_read_lock) },
	{ 0xf229424a, __VMLINUX_SYMBOL_STR(preempt_count_add) },
	{ 0x20014154, __VMLINUX_SYMBOL_STR(ip_queue_xmit) },
	{ 0x7b94b5ed, __VMLINUX_SYMBOL_STR(dccp_v4_connect) },
	{ 0xd542439, __VMLINUX_SYMBOL_STR(__ipv6_addr_type) },
	{ 0xab1e8d13, __VMLINUX_SYMBOL_STR(inet6_csk_addr2sockaddr) },
	{ 0x894353e7, __VMLINUX_SYMBOL_STR(inet6_destroy_sock) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=dccp,dccp_ipv4";

